######################################################################
# Automatically generated by qmake (2.01a) Mon Aug 3 14:30:07 2015
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += CalculatorDlg.h
FORMS += CalculatorDlg.ui
SOURCES += CalculatorDlg.cpp main.cpp
