#!/bin/sh
#
# autogen.sh - provides automatic build system preparation
#              for use with the GNU build system
#
# -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
#                          _ _
#                         | | |__
#                         | | '_ \
#                         | | |_) |
#                         |_|_.__/
#
# 'lb' is a Libevent-based benchmarking tool for HTTP servers
#
#                (C) Copyright 2009-2016
#  Rocco Carbone <rocco /at/ tecsiel /dot/ it>, Pisa, Italy
#
# Released under the terms of 3-clause BSD License.
# See included LICENSE file for details.
#
# -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
#


# The name of this program.
progname=`echo "$0" | sed 's%^.*/%%'`

help="Try \`$progname --help' for more information"

for arg
do
  case "$arg" in
  -h | --help)
    cat <<EOF
Usage: $progname [OPTION]...

This shell script helps you to configure 'lb'

-h, --help            display this message and exit
-p, --purge           purge all files which are not part of the source package

EOF
    exit 0
    ;;

  esac
done

#
# 1. Cleanup from previuos run
#
if [ -f Makefile ]; then
  echo "#!/bin/sh" > config.status
  make -k distclean > /dev/null 2>&1
fi

# the usual garbage
rm -f *~

# Generated by configure
rm -f version-lb.h
rm -f Makefile
rm -f site-lb.h
rm -f stamp-h1
rm -f config.log config.status
rm -f libtool
rm -rf .deps

# Generated by autoconf
rm -f configure

# Generated by automake
rm -f Makefile.in
rm -f config.guess
rm -f config.sub
rm -f depcomp
rm -f install-sh
rm -f missing

# Generated by autoheader
rm -f site-lb.h.in

# Generated by aclocal
rm -rf autom4te.cache
rm -f aclocal.m4

# Generated by libtoolize
rm -f ltmain.sh
rm -rf m4

if [ $# != 0 ]; then
  case $1 in
    -p | --purge)
      shift
      exit 0
    ;;
 esac
fi

echo "Running autogen.sh implies you are a developer, congratulations!"

echo
echo "Preparing the build system... please wait"
echo

# Create an empty m4 directory just for backward compatibility with very old GNU tools
mkdir m4

#
# 2. Prepare the package to use libtool
#
echo "Running libtoolize..."; (libtoolize --copy --force --quiet || glibtoolize --copy --force --quiet) || exit 1

#
# 3. Scan configure.ac to create aclocal.m4
#
echo "Running aclocal......"; aclocal -I m4 || exit 1

#
# 4. Generate the template configuration file of C `#define' statements
#
echo "Running autoheader..."; autoheader --force || exit 1

#
# 5. Generate Makefile.in from Makefile.am
#
echo "Running automake....."; automake --add-missing --copy --gnu > /dev/null 2>&1 || exit 1

#
# 6. Generate the configuration script
#
echo "Running autoconf....."; autoconf || exit 1

# Remove autoconf 2.6x's cache directory
rm -rf autom4te.cache

echo
echo "The build system is now ready.  To build, please run:"
echo "you@office 1> configure --with-libevent=<libevent-2.x.y development directory>"
echo "you@office 2> make"
echo
echo "Have fun!"
echo "/rocco"
