#!/bin/sh

echo -n Try to bring eth2 interface up......>/dev/ttySAC2

if [ -f /etc/eth2-setting ] ; then
	source /etc/eth2-setting

             #if grep -q "^/dev/root / nfs " /etc/mtab ; then
              if grep -q "root=/dev/nfs" /proc/cmdline;then
		echo -n NFS root ... > /dev/ttySAC2
	else
		ifconfig eth2 down
		ifconfig eth2 hw ether $MAC
		ifconfig eth2 $IP netmask $Mask up
		route add default gw $Gateway
	fi

	echo nameserver $DNS > /etc/resolv.conf
else

	if grep -q "^/dev/root / nfs " /etc/mtab ; then
		echo -n NFS root ... > /dev/ttySAC2
	else
	/sbin/ifconfig eth2 192.168.0.254 netmask 255.255.255.0 up
	fi
fi

echo Done > /dev/ttySAC2
