#! /bin/sh
PATH=/sbin:/bin:/usr/sbin:/usr/bin:/usr/local/bin:
runlevel=S
prevlevel=N
umask 022
export PATH runlevel prevlevel

#
#	Trap CTRL-C &c only in this shell so we can interrupt subprocesses.
#
trap ":" INT QUIT TSTP
/bin/hostname rdmcu

/bin/mount -n -t proc none /proc
/bin/mount -n -t sysfs none /sys
/bin/mount -n -t usbfs none /proc/bus/usb
/bin/mount -t ramfs none /dev

echo /sbin/mdev > /proc/sys/kernel/hotplug
/sbin/mdev -s
/bin/hotplug
# mounting file system specified in /etc/fstab
mkdir -p /dev/pts
mkdir -p /dev/shm
/bin/mount -n -t devpts none /dev/pts -o mode=0622
/bin/mount -n -t tmpfs tmpfs /dev/shm
/bin/mount -n -t ramfs none /tmp
/bin/mount -n -t ramfs none /var
mkdir -p /var/empty
mkdir -p /var/log
mkdir -p /var/log/boa
mkdir -p /var/lock
mkdir -p /var/run
mkdir -p /var/tmp

/sbin/hwclock -s -f /dev/rtc

syslogd

# run inetd server
/etc/rc.d/init.d/netd start

#/etc/rc.d/init.d/alsaconf start
#/etc/amixer.sh

echo "                        " > /dev/tty1
echo "Starting networking..." > /dev/tty1

/sbin/ifconfig lo 127.0.0.1
/etc/init.d/ifconfig-eth0
/etc/init.d/ifconfig-eth1
/etc/init.d/ifconfig-eth2
ip a add 192.168.1.232/16 dev eth0

mkdir -p /lib/modules/3.0.15

#start ftp server user:root password:
/sbin/vsftpd &

#start telnetd server usr:root password:
/sbin/telnetd 

#start boa web service
/sbin/boa

#linein xyzxyz added
/usr/alsa/alsautil/sbin/alsactl restore
#insmod /lib/modules/wlan.ko

export set HOME=/root
export set QTDIR=/opt/qt
export set QPEDIR=/opt/qtopia
export set QWS_KEYBOARD="USB:/dev/input/event1"
#export set QWS_MOUSE_PROTO="USB:/dev/input/mouse0"
export set QWS_MOUSE_PROTO="TPanel:/dev/misc/touchpanel"
#export set QWS_MOUSE_PROTO="USB:/dev/h3600_tsraw"
export set PATH=$QPEDIR/bin:$PATH
export set LD_LIBRARY_PATH=$QTDIR/lib:$QPEDIR/lib


echo "                                  " > /dev/tty1
echo "Starting Qtopia2, please waiting..." > /dev/tty1
echo "                                  "
echo "Starting Qtopia2, please waiting..." 

mkdir /var/rtud/
/sbin/rtud start
/bin/qtopia &

PID=`netstat -lnp | grep 21 | awk '{print $7}' | awk -F '/' '{print $1}'`
echo ${PID} > /var/run/vsftpd.pid

PID=`netstat -lnp | grep 23 | awk '{print $7}' | awk -F '/' '{print $1}'`
echo ${PID} > /var/run/telnetd.pid

chmod 0700 /etc/monitrc
/sbin/monit -c /etc/monitrc -d 10 
