######################################################################
# Automatically generated by qmake (3.0) ??? ?? 3 11:47:52 2019
######################################################################

TEMPLATE = app
TARGET = selfdefine
DEPENDPATH += .
INCLUDEPATH += .
CONFIG += console

# Input
HEADERS += newspaper.h reader.h
SOURCES += main.cpp
