######################################################################
# Automatically generated by qmake (2.01a) Fri Jul 31 13:43:26 2015
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += hello.cpp
