#!/bin/sh
IPV4_REGEX="[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}"
#curl -s http://site.ip138.com/domain/read.do?domain=$1 | sed -n 's/.*ip\":\"\([^"]*\).*$/\1/p' 2>/dev/null
curl -s http://site.ip138.com/domain/read.do?domain=$1 2>/dev/null | sed -ne "s/.*:\"\($IPV4_REGEX\)\".*$/\1/p"
#echo "192.168.9.1"
exit 0

#whois:
#curl -s --data 'WhoisRequest=www.google.com' https://ipinfo.info/ipchecker/index.php
#<br> IP Address:ip<br>
#site_ip:
#http://site.ip138.com/domain/read.do?domain=ipipip.ddns.com
#{"ip":"1.2.3.4",
