#!/bin/sh

curl -s http://1212.ip138.com/ic.asp 2>/dev/null | sed -ne "s/.*\[\(.*\)\].*$/\1/p"
#upnpc -s | grep "ExternalIPAddress" | sed 's/[^0-9\.]//g'

#myip:
#http://1212.ip138.com/ic.asp
#.*IP.*[ip].*$
#curl -s http://checkip.dns.he.net
#^Your IP address is : 101.248.255.208</body>$
#https://submit.apnic.net/templates/yourip.html
#^[<strong>ip</strong>]$
#https://ipinfo.info/ipn/
#<h4>203.104.193.100<br>
