/*  We'll start by writing the function which reacts to the signal
    which is passed in the parameter sig.
    This is the function we will arrange to be called when a signal occurs.
    We print a message, then reset the signal handling for SIGINT
    (by default generated by pressing CTRL-C) back to the default behavior.
    Let's call this function ouch.  */

#include <signal.h>
#include <stdio.h>
#include <unistd.h>

void ouch(int sig)
{
    printf("OUCH! - I got signal %d\n", sig);
    (void) signal(SIGINT, SIG_DFL);
}

/*  The main function has to intercept the SIGINT signal generated when we type Ctrl-C .
    For the rest of the time, it just sits in an infinite loop,
    printing a message once a second. 
当程序没有被杀的时候，它将一直执行while(1)循环，当程序被杀的时候，
它会执行信号请求的函数
    */

int main(void)
{
//	SIGINT代表Ctrl+C信号
    (void) signal(SIGINT, ouch);

	 kill(2083, SIGINT);
    while(1) 
	{
        printf("Hello World!\n");
        sleep(1);
    }
	
#if 0
	(void) signal(SIGINT, ouch);
    while(1) {
        printf("Hello Me!\n");
        sleep(1);
    }
#endif
}
//	程序运行起来的时候，它就会不停的打印Hello World
//	当程序被杀的时候，(void) signal(SIGINT, ouch);就会收到信号
//	然后程序继续执行，当程序再次被杀的时候，它就会被杀。
