language: bash

addons:
  apt:
    packages:
      - doxygen

env:
  global:
  - export PATH="/usr/local/bin:$PATH"

before_install:
- |
  if [ "$TRAVIS_OS_NAME" = "linux" ]; then
    tag=1.1.0
    batstmp="$(mktemp -d bats-core-"${tag}".XXXXX)"
    pushd "${batstmp}" &> /dev/null || return 11
    curl -sSLO https://github.com/bats-core/bats-core/archive/v"${tag}".tar.gz
    tar -zxvf v"${tag}".tar.gz
    sudo bash "${batstmp}"/bats-core-"${tag}"/install.sh /usr/local
    popd &> /dev/null || return 12
    command -v bats && rm -rf "${batstmp}"
  fi

jobs:
  include:
    - stage: ShellCheck
      script: shellcheck lib/bsfl.sh
    - stage: Test
      script: bats test/
    - stage: Documentation
      script: cd doc && doxygen Doxyfile
      deploy:
        provider: pages
        github-token:
          secure: "YRuWwhnK0baQtRI5f+Hu68jtU9rwgMEPUjMs8PA2fvSZz4dd4kM3Z8jK2iiVfiQ4SUCg9HLtm9h6PGiibIcDYWtQN1e+9kSEJMnpf3oxPlPRAVuyCY/mRzdPUsA0mD9tKh9nTlPjvuVr89yKFLnNHrOmqjBbTEsZ6FMp58FlG9gMCZ06ehDX6FkL7H1m6SSSJkMZDBx00xQSatLBIaHsaTTSttvyhw6r2HZvaiYAOjW5WtgG8phqrrq/Hjfd12+vF1p8/A3iUa0Nkyqbc6SwIHuId1IWcP/esUdhMAlOWUxdekajoLzDYP1YoJbfmFbB6l6/vzsRhzqNDudx4PlkUp7/Z/PG1ob/ijhadkGMTrYOYFOHDdyriZY04t+zj2q6kINuis+nT1k9j2tO/7P2E4R928saoCFiJbydCjdxuTbFXdkzPI23QlIE5avzH9Z5yPu48clcFcZSJjuBP3EaByJ7uQLSgeHIZrd/uRH4xNfyJ9IbLmBio4dNCqca/isZ9GFt+Y0lK9U/OxcSwMfiGpZKeO5IPp8QurKUsgwMPSYiyx8l4FteY4x4V5Hpt3kp1R/i8VPfEg601sv+/7WQJSAvWt4GpoCm73t6Vda7HfAy253walYiioK+aL7QNpaXw3Un37RUQFooIK57VjLGkZzh9FqFc1PdbLop00984Yk="
        local-dir: doc/html
        cleanup: false
        skip-cleanup: true
        on:
          branch: master
          tags: true
          repo: SkypLabs/bsfl

notifications:
  email:
    on_success: never
