all:
	@echo "[1;35m\$$(MAKE_VERSION)[0m = $(MAKE_VERSION)"
	@echo "[1;35m\$$(MAKECMDGOALS)[0m = $(MAKECMDGOALS)"
	@echo "[1;35m\$$(MAKELEVEL)[0m = $(MAKELEVEL)"
	@echo "[1;35m\$$(CURDIR)[0m = $(CURDIR)"
	@echo "[1;35m\$$(CC)[0m = $(CC)"
	@echo "[1;35m\$$(LD)[0m = $(LD)"
	@echo "[1;35m\$$(AR)[0m = $(AR)"
	@echo "[1;35m\$$(CFLAGS)[0m = $(CFLAGS)"
	@echo "[1;35m\$$(CCFLAGS)[0m = $(LDFLAGS)"
	@echo ""

clean:
	@echo "\$$(MAKECMDGOALS) = $(MAKECMDGOALS)"

