language: php
php:
  - 5.5
before_install:
  - sudo add-apt-repository ppa:duggan/bats --yes
  - sudo apt-get update -qq
  - sudo apt-get install -qq bats
  - sudo ln -s "$(pwd)/bin/bash-utils" /usr/local/bin/
  - git clone https://github.com/e-picas/markdown-extended.git /tmp/markdown-extended
  - sudo ln -s /tmp/markdown-extended/bin/markdown-extended /usr/local/bin/
script:
  - make tests
branches:
  only:
    - master
    - dev
    - dev-modules
notifications:
  email:
    on_success: never
