######################################################################
# Automatically generated by qmake (2.01a) Mon Aug 3 13:25:48 2015
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += time.h
SOURCES += main.cpp time.cpp
