engines:
  shellcheck:
    enabled: true
    checks:
      SC1090:
        enabled: false
      SC2034:
        enabled: false
      SC2153:
        enabled: false
      SC2086:
        enabled: false
      SC2154:
        enabled: false
