language: node_js
node_js:
- '10'
before_install:
- npm install -g auto-changelog
install:
- auto-changelog
- ls -al
- cat CHANGELOG.md
deploy:
  provider: npm
  edge: true
  email: vi@ole.org
  api_key:
    secure: KPLN8i8W9bfl8HX+iXEIQkNEydvNX96HMnpGhIZhN6OSl0qqei+i14HivTAQm7ybpT82qjSdNeL7psaydStDdeTI1+KA2JfKYjAyQXq4TqkFaqnAFXlU9z6fNROf0STNkwtLWectpaavvnuxD5F/4RUTC9eK6NI2Os6izpbwXcq3hJMDk77vkAWx33L93nk7aK+pnS/Di3bnNkSzGUZaqK/GKHVnmxJ7r5m6dtjPtw2E5osaxDCob3JfZUoHn+Mk4bvhpikNphac51QY7imuADotjjqfmTOA7nPCHTjpH6n9ZZLkCHZ8S3ofDpf5eWBSbnsO18dOreBBAgTa6QGWzZ+2jvsUvmTp+ka6Gyp+loKGU5U477QJF4HQIB3V+wr4S7rb8Z0560Pr+0Ht88l9J82ObP8AfbO1iAH8axlr06jPDeu04B3AUM2MiuQRQ9rS4+S5nO5FpYSKh/hBlTg4GJG8X427N9TevBup2AZo/kZGAh7Di8/vIWYBKmAYDyEJwfsZfGozMD1APcTu3VDEgUaZlZSTUEJs9MAOMFh0cgHWbrUexrSfAdQMcXTcsg67gRGg70hR2OHt7At77YjrYRDvNUFyRKAJ5yUH/ZuMTwsuUqlJmC2RPV0iLdT6Qo6IuELwoGk8Moc4D5WoH0zX83WE/nk1Q4PQXt7soUaI6U0=
  on:
    tags: true
    repo: treehouses/cli
