all: dir suffix basename addsuffix addprefix

dir:
	@echo -e "(\033[1;33mdir\033[0m <filename...>)"
	@echo -e "'$(dir Makefile.filename)'"
	@echo -e ""

suffix:
	@echo -e "(\033[1;33msuffix\033[0m <filename...>)"
	@echo -e "'$(suffix Makefile.filename)'"
	@echo -e ""

basename:
	@echo -e "(\033[1;33mbasename\033[0m <filename...>)"
	@echo -e "'$(basename Makefile.filename)'"
	@echo -e ""

addsuffix:
	@echo -e "(\033[1;33maddsuffix\033[0m <suffix>,<filename...>)"
	@echo -e "'$(addsuffix .bak, Makefile.filename)'"
	@echo -e ""

addprefix:
	@echo -e "(\033[1;33maddprefix\033[0m <prefix>,<filename...>)"
	@echo -e "'$(addprefix /tmp/, Makefile.filename)'"
	@echo -e ""