PWD = $(shell pwd)


# string substitute
TEXT_IN  = $(PWD)
FROM     = $(notdir $(PWD))
TO       = substitute
TEXT_OUT = $(subst $(FROM),$(TO),$(TEXT_IN))


all:
	@echo -e "(\033[1;33msubst\033[0m <from>,<to>,<text>)"
	@echo -e "$(TEXT_IN) -> $(TEXT_OUT)"
	@echo -e ""