######################################################################
# Automatically generated by qmake (2.01a) Mon Aug 3 10:08:19 2015
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += Dialog.cpp
