# Makefile Copyright 2008 Groetker, Holtmann, Keding, Wloka
# gcc -Wall -o testmalloc -DUSE_NEW -g testmalloc.c
include ../../Makefile.include

testmalloc:
	gcc -Wall -o testmalloc -g testmalloc.c

clean:
	rm -rf $(CLEAN_TARGETS) testmalloc
