/* The opcodes used in PXDScript */
#define nopC 0
#define imulC 1
#define inegC 2
#define iremC 3
#define isubC 4
#define idivC 5
#define iaddC 6
#define aaddC 7
#define gotoC 8
#define ifeqC 9
#define ifneC 10
#define if_acmpeqC 11
#define if_acmpneC 12
#define if_icmpeqC 13
#define if_icmpgtC 14
#define if_icmpltC 15
#define if_icmpleC 16
#define if_icmpgeC 17
#define if_icmpneC 18
#define ireturnC 19
#define areturnC 20
#define returnC 21
#define aloadC 22
#define astoreC 23
#define iloadC 24
#define istoreC 25
#define ldc_intC 26
#define iconst_0C 27
#define iconst_1C 28
#define iconst_2C 29
#define iconst_3C 30
#define iconst_4C 31
#define iconst_5C 32
#define ldc_stringC 33
#define dupC 34
#define popC 35
#define callC 36
#define setint_mdlC 37
#define setint_particleC 38
#define setint_plyC 39
#define setint_lightC 40
#define setint_camC 41
#define sleepC 42
#define sleep_trigC 43
#define cast_inttostringC 44
#define cast_stringtointC 45
#define cast_booltostringC 46
