#!/usr/bin/env bash
printf "%d args:" $#
printf " <%s>" "$@"
echo

# $ var="This is an example"
# $ showarg $var
# 4 args: <This> <is> <an> <example>
# 
# $ var="This/is/an/example"
# $ showarg $var
# 1 args: <This/is/an/example>

# $ IFS=/
# $ var="This/is/an/example"
# $ showarg $var
# 4 args: <This> <is> <an> <example>