/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: IM.Instant.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "IM.Instant.pb-c.h"
void authentication_req__init (AuthenticationReq * message) {
    static const AuthenticationReq init_value = AUTHENTICATION_REQ__INIT;
    *message = init_value;
}

size_t authentication_req__get_packed_size (const AuthenticationReq * message) {
    assert (message->base.descriptor == &authentication_req__descriptor);
    return protobuf_c_message_get_packed_size ((const ProtobufCMessage *) (message));
}

size_t authentication_req__pack (const AuthenticationReq * message, uint8_t * out) {
    assert (message->base.descriptor == &authentication_req__descriptor);
    return protobuf_c_message_pack ((const ProtobufCMessage *) message, out);
}

size_t authentication_req__pack_to_buffer (const AuthenticationReq * message, ProtobufCBuffer * buffer) {
    assert (message->base.descriptor == &authentication_req__descriptor);
    return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage *) message, buffer);
}

AuthenticationReq *authentication_req__unpack (ProtobufCAllocator * allocator, size_t len, const uint8_t * data) {
    return (AuthenticationReq *)
        protobuf_c_message_unpack (&authentication_req__descriptor, allocator, len, data);
}

void authentication_req__free_unpacked (AuthenticationReq * message, ProtobufCAllocator * allocator) {
    if (!message)
        return;
    assert (message->base.descriptor == &authentication_req__descriptor);
    protobuf_c_message_free_unpacked ((ProtobufCMessage *) message, allocator);
}

void authentication_rsp__init (AuthenticationRsp * message) {
    static const AuthenticationRsp init_value = AUTHENTICATION_RSP__INIT;
    *message = init_value;
}

size_t authentication_rsp__get_packed_size (const AuthenticationRsp * message) {
    assert (message->base.descriptor == &authentication_rsp__descriptor);
    return protobuf_c_message_get_packed_size ((const ProtobufCMessage *) (message));
}

size_t authentication_rsp__pack (const AuthenticationRsp * message, uint8_t * out) {
    assert (message->base.descriptor == &authentication_rsp__descriptor);
    return protobuf_c_message_pack ((const ProtobufCMessage *) message, out);
}

size_t authentication_rsp__pack_to_buffer (const AuthenticationRsp * message, ProtobufCBuffer * buffer) {
    assert (message->base.descriptor == &authentication_rsp__descriptor);
    return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage *) message, buffer);
}

AuthenticationRsp *authentication_rsp__unpack (ProtobufCAllocator * allocator, size_t len, const uint8_t * data) {
    return (AuthenticationRsp *)
        protobuf_c_message_unpack (&authentication_rsp__descriptor, allocator, len, data);
}

void authentication_rsp__free_unpacked (AuthenticationRsp * message, ProtobufCAllocator * allocator) {
    if (!message)
        return;
    assert (message->base.descriptor == &authentication_rsp__descriptor);
    protobuf_c_message_free_unpacked ((ProtobufCMessage *) message, allocator);
}

void logout_req__init (LogoutReq * message) {
    static const LogoutReq init_value = LOGOUT_REQ__INIT;
    *message = init_value;
}

size_t logout_req__get_packed_size (const LogoutReq * message) {
    assert (message->base.descriptor == &logout_req__descriptor);
    return protobuf_c_message_get_packed_size ((const ProtobufCMessage *) (message));
}

size_t logout_req__pack (const LogoutReq * message, uint8_t * out) {
    assert (message->base.descriptor == &logout_req__descriptor);
    return protobuf_c_message_pack ((const ProtobufCMessage *) message, out);
}

size_t logout_req__pack_to_buffer (const LogoutReq * message, ProtobufCBuffer * buffer) {
    assert (message->base.descriptor == &logout_req__descriptor);
    return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage *) message, buffer);
}

LogoutReq *logout_req__unpack (ProtobufCAllocator * allocator, size_t len, const uint8_t * data) {
    return (LogoutReq *)
        protobuf_c_message_unpack (&logout_req__descriptor, allocator, len, data);
}

void logout_req__free_unpacked (LogoutReq * message, ProtobufCAllocator * allocator) {
    if (!message)
        return;
    assert (message->base.descriptor == &logout_req__descriptor);
    protobuf_c_message_free_unpacked ((ProtobufCMessage *) message, allocator);
}

void logout_rsp__init (LogoutRsp * message) {
    static const LogoutRsp init_value = LOGOUT_RSP__INIT;
    *message = init_value;
}

size_t logout_rsp__get_packed_size (const LogoutRsp * message) {
    assert (message->base.descriptor == &logout_rsp__descriptor);
    return protobuf_c_message_get_packed_size ((const ProtobufCMessage *) (message));
}

size_t logout_rsp__pack (const LogoutRsp * message, uint8_t * out) {
    assert (message->base.descriptor == &logout_rsp__descriptor);
    return protobuf_c_message_pack ((const ProtobufCMessage *) message, out);
}

size_t logout_rsp__pack_to_buffer (const LogoutRsp * message, ProtobufCBuffer * buffer) {
    assert (message->base.descriptor == &logout_rsp__descriptor);
    return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage *) message, buffer);
}

LogoutRsp *logout_rsp__unpack (ProtobufCAllocator * allocator, size_t len, const uint8_t * data) {
    return (LogoutRsp *)
        protobuf_c_message_unpack (&logout_rsp__descriptor, allocator, len, data);
}

void logout_rsp__free_unpacked (LogoutRsp * message, ProtobufCAllocator * allocator) {
    if (!message)
        return;
    assert (message->base.descriptor == &logout_rsp__descriptor);
    protobuf_c_message_free_unpacked ((ProtobufCMessage *) message, allocator);
}

void member_recd__init (MemberRecd * message) {
    static const MemberRecd init_value = MEMBER_RECD__INIT;
    *message = init_value;
}

size_t member_recd__get_packed_size (const MemberRecd * message) {
    assert (message->base.descriptor == &member_recd__descriptor);
    return protobuf_c_message_get_packed_size ((const ProtobufCMessage *) (message));
}

size_t member_recd__pack (const MemberRecd * message, uint8_t * out) {
    assert (message->base.descriptor == &member_recd__descriptor);
    return protobuf_c_message_pack ((const ProtobufCMessage *) message, out);
}

size_t member_recd__pack_to_buffer (const MemberRecd * message, ProtobufCBuffer * buffer) {
    assert (message->base.descriptor == &member_recd__descriptor);
    return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage *) message, buffer);
}

MemberRecd *member_recd__unpack (ProtobufCAllocator * allocator, size_t len, const uint8_t * data) {
    return (MemberRecd *)
        protobuf_c_message_unpack (&member_recd__descriptor, allocator, len, data);
}

void member_recd__free_unpacked (MemberRecd * message, ProtobufCAllocator * allocator) {
    if (!message)
        return;
    assert (message->base.descriptor == &member_recd__descriptor);
    protobuf_c_message_free_unpacked ((ProtobufCMessage *) message, allocator);
}

void notify_friends_rsp__init (NotifyFriendsRsp * message) {
    static const NotifyFriendsRsp init_value = NOTIFY_FRIENDS_RSP__INIT;
    *message = init_value;
}

size_t notify_friends_rsp__get_packed_size (const NotifyFriendsRsp * message) {
    assert (message->base.descriptor == &notify_friends_rsp__descriptor);
    return protobuf_c_message_get_packed_size ((const ProtobufCMessage *) (message));
}

size_t notify_friends_rsp__pack (const NotifyFriendsRsp * message, uint8_t * out) {
    assert (message->base.descriptor == &notify_friends_rsp__descriptor);
    return protobuf_c_message_pack ((const ProtobufCMessage *) message, out);
}

size_t notify_friends_rsp__pack_to_buffer (const NotifyFriendsRsp * message, ProtobufCBuffer * buffer) {
    assert (message->base.descriptor == &notify_friends_rsp__descriptor);
    return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage *) message, buffer);
}

NotifyFriendsRsp *notify_friends_rsp__unpack (ProtobufCAllocator * allocator, size_t len, const uint8_t * data) {
    return (NotifyFriendsRsp *)
        protobuf_c_message_unpack (&notify_friends_rsp__descriptor, allocator, len, data);
}

void notify_friends_rsp__free_unpacked (NotifyFriendsRsp * message, ProtobufCAllocator * allocator) {
    if (!message)
        return;
    assert (message->base.descriptor == &notify_friends_rsp__descriptor);
    protobuf_c_message_free_unpacked ((ProtobufCMessage *) message, allocator);
}

void friend_list_rsp__init (FriendListRsp * message) {
    static const FriendListRsp init_value = FRIEND_LIST_RSP__INIT;
    *message = init_value;
}

size_t friend_list_rsp__get_packed_size (const FriendListRsp * message) {
    assert (message->base.descriptor == &friend_list_rsp__descriptor);
    return protobuf_c_message_get_packed_size ((const ProtobufCMessage *) (message));
}

size_t friend_list_rsp__pack (const FriendListRsp * message, uint8_t * out) {
    assert (message->base.descriptor == &friend_list_rsp__descriptor);
    return protobuf_c_message_pack ((const ProtobufCMessage *) message, out);
}

size_t friend_list_rsp__pack_to_buffer (const FriendListRsp * message, ProtobufCBuffer * buffer) {
    assert (message->base.descriptor == &friend_list_rsp__descriptor);
    return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage *) message, buffer);
}

FriendListRsp *friend_list_rsp__unpack (ProtobufCAllocator * allocator, size_t len, const uint8_t * data) {
    return (FriendListRsp *)
        protobuf_c_message_unpack (&friend_list_rsp__descriptor, allocator, len, data);
}

void friend_list_rsp__free_unpacked (FriendListRsp * message, ProtobufCAllocator * allocator) {
    if (!message)
        return;
    assert (message->base.descriptor == &friend_list_rsp__descriptor);
    protobuf_c_message_free_unpacked ((ProtobufCMessage *) message, allocator);
}

void register_req__init (RegisterReq * message) {
    static const RegisterReq init_value = REGISTER_REQ__INIT;
    *message = init_value;
}

size_t register_req__get_packed_size (const RegisterReq * message) {
    assert (message->base.descriptor == &register_req__descriptor);
    return protobuf_c_message_get_packed_size ((const ProtobufCMessage *) (message));
}

size_t register_req__pack (const RegisterReq * message, uint8_t * out) {
    assert (message->base.descriptor == &register_req__descriptor);
    return protobuf_c_message_pack ((const ProtobufCMessage *) message, out);
}

size_t register_req__pack_to_buffer (const RegisterReq * message, ProtobufCBuffer * buffer) {
    assert (message->base.descriptor == &register_req__descriptor);
    return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage *) message, buffer);
}

RegisterReq *register_req__unpack (ProtobufCAllocator * allocator, size_t len, const uint8_t * data) {
    return (RegisterReq *)
        protobuf_c_message_unpack (&register_req__descriptor, allocator, len, data);
}

void register_req__free_unpacked (RegisterReq * message, ProtobufCAllocator * allocator) {
    if (!message)
        return;
    assert (message->base.descriptor == &register_req__descriptor);
    protobuf_c_message_free_unpacked ((ProtobufCMessage *) message, allocator);
}

void register_rsp__init (RegisterRsp * message) {
    static const RegisterRsp init_value = REGISTER_RSP__INIT;
    *message = init_value;
}

size_t register_rsp__get_packed_size (const RegisterRsp * message) {
    assert (message->base.descriptor == &register_rsp__descriptor);
    return protobuf_c_message_get_packed_size ((const ProtobufCMessage *) (message));
}

size_t register_rsp__pack (const RegisterRsp * message, uint8_t * out) {
    assert (message->base.descriptor == &register_rsp__descriptor);
    return protobuf_c_message_pack ((const ProtobufCMessage *) message, out);
}

size_t register_rsp__pack_to_buffer (const RegisterRsp * message, ProtobufCBuffer * buffer) {
    assert (message->base.descriptor == &register_rsp__descriptor);
    return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage *) message, buffer);
}

RegisterRsp *register_rsp__unpack (ProtobufCAllocator * allocator, size_t len, const uint8_t * data) {
    return (RegisterRsp *)
        protobuf_c_message_unpack (&register_rsp__descriptor, allocator, len, data);
}

void register_rsp__free_unpacked (RegisterRsp * message, ProtobufCAllocator * allocator) {
    if (!message)
        return;
    assert (message->base.descriptor == &register_rsp__descriptor);
    protobuf_c_message_free_unpacked ((ProtobufCMessage *) message, allocator);
}

void add_friend_req__init (AddFriendReq * message) {
    static const AddFriendReq init_value = ADD_FRIEND_REQ__INIT;
    *message = init_value;
}

size_t add_friend_req__get_packed_size (const AddFriendReq * message) {
    assert (message->base.descriptor == &add_friend_req__descriptor);
    return protobuf_c_message_get_packed_size ((const ProtobufCMessage *) (message));
}

size_t add_friend_req__pack (const AddFriendReq * message, uint8_t * out) {
    assert (message->base.descriptor == &add_friend_req__descriptor);
    return protobuf_c_message_pack ((const ProtobufCMessage *) message, out);
}

size_t add_friend_req__pack_to_buffer (const AddFriendReq * message, ProtobufCBuffer * buffer) {
    assert (message->base.descriptor == &add_friend_req__descriptor);
    return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage *) message, buffer);
}

AddFriendReq *add_friend_req__unpack (ProtobufCAllocator * allocator, size_t len, const uint8_t * data) {
    return (AddFriendReq *)
        protobuf_c_message_unpack (&add_friend_req__descriptor, allocator, len, data);
}

void add_friend_req__free_unpacked (AddFriendReq * message, ProtobufCAllocator * allocator) {
    if (!message)
        return;
    assert (message->base.descriptor == &add_friend_req__descriptor);
    protobuf_c_message_free_unpacked ((ProtobufCMessage *) message, allocator);
}

void friend_status_rsp__init (FriendStatusRsp * message) {
    static const FriendStatusRsp init_value = FRIEND_STATUS_RSP__INIT;
    *message = init_value;
}

size_t friend_status_rsp__get_packed_size (const FriendStatusRsp * message) {
    assert (message->base.descriptor == &friend_status_rsp__descriptor);
    return protobuf_c_message_get_packed_size ((const ProtobufCMessage *) (message));
}

size_t friend_status_rsp__pack (const FriendStatusRsp * message, uint8_t * out) {
    assert (message->base.descriptor == &friend_status_rsp__descriptor);
    return protobuf_c_message_pack ((const ProtobufCMessage *) message, out);
}

size_t friend_status_rsp__pack_to_buffer (const FriendStatusRsp * message, ProtobufCBuffer * buffer) {
    assert (message->base.descriptor == &friend_status_rsp__descriptor);
    return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage *) message, buffer);
}

FriendStatusRsp *friend_status_rsp__unpack (ProtobufCAllocator * allocator, size_t len, const uint8_t * data) {
    return (FriendStatusRsp *)
        protobuf_c_message_unpack (&friend_status_rsp__descriptor, allocator, len, data);
}

void friend_status_rsp__free_unpacked (FriendStatusRsp * message, ProtobufCAllocator * allocator) {
    if (!message)
        return;
    assert (message->base.descriptor == &friend_status_rsp__descriptor);
    protobuf_c_message_free_unpacked ((ProtobufCMessage *) message, allocator);
}

void acceptance_friend_req__init (AcceptanceFriendReq * message) {
    static const AcceptanceFriendReq init_value = ACCEPTANCE_FRIEND_REQ__INIT;
    *message = init_value;
}

size_t acceptance_friend_req__get_packed_size (const AcceptanceFriendReq * message) {
    assert (message->base.descriptor == &acceptance_friend_req__descriptor);
    return protobuf_c_message_get_packed_size ((const ProtobufCMessage *) (message));
}

size_t acceptance_friend_req__pack (const AcceptanceFriendReq * message, uint8_t * out) {
    assert (message->base.descriptor == &acceptance_friend_req__descriptor);
    return protobuf_c_message_pack ((const ProtobufCMessage *) message, out);
}

size_t acceptance_friend_req__pack_to_buffer (const AcceptanceFriendReq * message, ProtobufCBuffer * buffer) {
    assert (message->base.descriptor == &acceptance_friend_req__descriptor);
    return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage *) message, buffer);
}

AcceptanceFriendReq *acceptance_friend_req__unpack (ProtobufCAllocator * allocator, size_t len, const uint8_t * data) {
    return (AcceptanceFriendReq *)
        protobuf_c_message_unpack (&acceptance_friend_req__descriptor, allocator, len, data);
}

void acceptance_friend_req__free_unpacked (AcceptanceFriendReq * message, ProtobufCAllocator * allocator) {
    if (!message)
        return;
    assert (message->base.descriptor == &acceptance_friend_req__descriptor);
    protobuf_c_message_free_unpacked ((ProtobufCMessage *) message, allocator);
}

void delete_friend_req__init (DeleteFriendReq * message) {
    static const DeleteFriendReq init_value = DELETE_FRIEND_REQ__INIT;
    *message = init_value;
}

size_t delete_friend_req__get_packed_size (const DeleteFriendReq * message) {
    assert (message->base.descriptor == &delete_friend_req__descriptor);
    return protobuf_c_message_get_packed_size ((const ProtobufCMessage *) (message));
}

size_t delete_friend_req__pack (const DeleteFriendReq * message, uint8_t * out) {
    assert (message->base.descriptor == &delete_friend_req__descriptor);
    return protobuf_c_message_pack ((const ProtobufCMessage *) message, out);
}

size_t delete_friend_req__pack_to_buffer (const DeleteFriendReq * message, ProtobufCBuffer * buffer) {
    assert (message->base.descriptor == &delete_friend_req__descriptor);
    return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage *) message, buffer);
}

DeleteFriendReq *delete_friend_req__unpack (ProtobufCAllocator * allocator, size_t len, const uint8_t * data) {
    return (DeleteFriendReq *)
        protobuf_c_message_unpack (&delete_friend_req__descriptor, allocator, len, data);
}

void delete_friend_req__free_unpacked (DeleteFriendReq * message, ProtobufCAllocator * allocator) {
    if (!message)
        return;
    assert (message->base.descriptor == &delete_friend_req__descriptor);
    protobuf_c_message_free_unpacked ((ProtobufCMessage *) message, allocator);
}

void delete_friend_rsp__init (DeleteFriendRsp * message) {
    static const DeleteFriendRsp init_value = DELETE_FRIEND_RSP__INIT;
    *message = init_value;
}

size_t delete_friend_rsp__get_packed_size (const DeleteFriendRsp * message) {
    assert (message->base.descriptor == &delete_friend_rsp__descriptor);
    return protobuf_c_message_get_packed_size ((const ProtobufCMessage *) (message));
}

size_t delete_friend_rsp__pack (const DeleteFriendRsp * message, uint8_t * out) {
    assert (message->base.descriptor == &delete_friend_rsp__descriptor);
    return protobuf_c_message_pack ((const ProtobufCMessage *) message, out);
}

size_t delete_friend_rsp__pack_to_buffer (const DeleteFriendRsp * message, ProtobufCBuffer * buffer) {
    assert (message->base.descriptor == &delete_friend_rsp__descriptor);
    return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage *) message, buffer);
}

DeleteFriendRsp *delete_friend_rsp__unpack (ProtobufCAllocator * allocator, size_t len, const uint8_t * data) {
    return (DeleteFriendRsp *)
        protobuf_c_message_unpack (&delete_friend_rsp__descriptor, allocator, len, data);
}

void delete_friend_rsp__free_unpacked (DeleteFriendRsp * message, ProtobufCAllocator * allocator) {
    if (!message)
        return;
    assert (message->base.descriptor == &delete_friend_rsp__descriptor);
    protobuf_c_message_free_unpacked ((ProtobufCMessage *) message, allocator);
}

void msg_req_rsp__init (MsgReqRsp * message) {
    static const MsgReqRsp init_value = MSG_REQ_RSP__INIT;
    *message = init_value;
}

size_t msg_req_rsp__get_packed_size (const MsgReqRsp * message) {
    assert (message->base.descriptor == &msg_req_rsp__descriptor);
    return protobuf_c_message_get_packed_size ((const ProtobufCMessage *) (message));
}

size_t msg_req_rsp__pack (const MsgReqRsp * message, uint8_t * out) {
    assert (message->base.descriptor == &msg_req_rsp__descriptor);
    return protobuf_c_message_pack ((const ProtobufCMessage *) message, out);
}

size_t msg_req_rsp__pack_to_buffer (const MsgReqRsp * message, ProtobufCBuffer * buffer) {
    assert (message->base.descriptor == &msg_req_rsp__descriptor);
    return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage *) message, buffer);
}

MsgReqRsp *msg_req_rsp__unpack (ProtobufCAllocator * allocator, size_t len, const uint8_t * data) {
    return (MsgReqRsp *)
        protobuf_c_message_unpack (&msg_req_rsp__descriptor, allocator, len, data);
}

void msg_req_rsp__free_unpacked (MsgReqRsp * message, ProtobufCAllocator * allocator) {
    if (!message)
        return;
    assert (message->base.descriptor == &msg_req_rsp__descriptor);
    protobuf_c_message_free_unpacked ((ProtobufCMessage *) message, allocator);
}

void unregister_req__init (UnregisterReq * message) {
    static const UnregisterReq init_value = UNREGISTER_REQ__INIT;
    *message = init_value;
}

size_t unregister_req__get_packed_size (const UnregisterReq * message) {
    assert (message->base.descriptor == &unregister_req__descriptor);
    return protobuf_c_message_get_packed_size ((const ProtobufCMessage *) (message));
}

size_t unregister_req__pack (const UnregisterReq * message, uint8_t * out) {
    assert (message->base.descriptor == &unregister_req__descriptor);
    return protobuf_c_message_pack ((const ProtobufCMessage *) message, out);
}

size_t unregister_req__pack_to_buffer (const UnregisterReq * message, ProtobufCBuffer * buffer) {
    assert (message->base.descriptor == &unregister_req__descriptor);
    return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage *) message, buffer);
}

UnregisterReq *unregister_req__unpack (ProtobufCAllocator * allocator, size_t len, const uint8_t * data) {
    return (UnregisterReq *)
        protobuf_c_message_unpack (&unregister_req__descriptor, allocator, len, data);
}

void unregister_req__free_unpacked (UnregisterReq * message, ProtobufCAllocator * allocator) {
    if (!message)
        return;
    assert (message->base.descriptor == &unregister_req__descriptor);
    protobuf_c_message_free_unpacked ((ProtobufCMessage *) message, allocator);
}

void unregister_rsp__init (UnregisterRsp * message) {
    static const UnregisterRsp init_value = UNREGISTER_RSP__INIT;
    *message = init_value;
}

size_t unregister_rsp__get_packed_size (const UnregisterRsp * message) {
    assert (message->base.descriptor == &unregister_rsp__descriptor);
    return protobuf_c_message_get_packed_size ((const ProtobufCMessage *) (message));
}

size_t unregister_rsp__pack (const UnregisterRsp * message, uint8_t * out) {
    assert (message->base.descriptor == &unregister_rsp__descriptor);
    return protobuf_c_message_pack ((const ProtobufCMessage *) message, out);
}

size_t unregister_rsp__pack_to_buffer (const UnregisterRsp * message, ProtobufCBuffer * buffer) {
    assert (message->base.descriptor == &unregister_rsp__descriptor);
    return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage *) message, buffer);
}

UnregisterRsp *unregister_rsp__unpack (ProtobufCAllocator * allocator, size_t len, const uint8_t * data) {
    return (UnregisterRsp *)
        protobuf_c_message_unpack (&unregister_rsp__descriptor, allocator, len, data);
}

void unregister_rsp__free_unpacked (UnregisterRsp * message, ProtobufCAllocator * allocator) {
    if (!message)
        return;
    assert (message->base.descriptor == &unregister_rsp__descriptor);
    protobuf_c_message_free_unpacked ((ProtobufCMessage *) message, allocator);
}

static const ProtobufCFieldDescriptor authentication_req__field_descriptors[2] = {
    {
     "user_name",
     1,
     PROTOBUF_C_LABEL_REQUIRED,
     PROTOBUF_C_TYPE_STRING,
     0,                         /* quantifier_offset */
     offsetof (AuthenticationReq, user_name),
     NULL,
     NULL,
     0,                         /* flags */
     0, NULL, NULL              /* reserved1,reserved2, etc */
     },
    {
     "password",
     2,
     PROTOBUF_C_LABEL_REQUIRED,
     PROTOBUF_C_TYPE_STRING,
     0,                         /* quantifier_offset */
     offsetof (AuthenticationReq, password),
     NULL,
     NULL,
     0,                         /* flags */
     0, NULL, NULL              /* reserved1,reserved2, etc */
     },
};

static const unsigned authentication_req__field_indices_by_name[] = {
    1,                          /* field[1] = password */
    0,                          /* field[0] = user_name */
};

static const ProtobufCIntRange authentication_req__number_ranges[1 + 1] = {
    {1, 0},
    {0, 2}
};

const ProtobufCMessageDescriptor authentication_req__descriptor = {
    PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
    "AuthenticationReq",
    "AuthenticationReq",
    "AuthenticationReq",
    "",
    sizeof (AuthenticationReq),
    2,
    authentication_req__field_descriptors,
    authentication_req__field_indices_by_name,
    1, authentication_req__number_ranges,
    (ProtobufCMessageInit) authentication_req__init,
    NULL, NULL, NULL            /* reserved[123] */
};

static const ProtobufCFieldDescriptor authentication_rsp__field_descriptors[1] = {
    {
     "auth",
     1,
     PROTOBUF_C_LABEL_REQUIRED,
     PROTOBUF_C_TYPE_INT32,
     0,                         /* quantifier_offset */
     offsetof (AuthenticationRsp, auth),
     NULL,
     NULL,
     0,                         /* flags */
     0, NULL, NULL              /* reserved1,reserved2, etc */
     },
};

static const unsigned authentication_rsp__field_indices_by_name[] = {
    0,                          /* field[0] = auth */
};

static const ProtobufCIntRange authentication_rsp__number_ranges[1 + 1] = {
    {1, 0},
    {0, 1}
};

const ProtobufCMessageDescriptor authentication_rsp__descriptor = {
    PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
    "AuthenticationRsp",
    "AuthenticationRsp",
    "AuthenticationRsp",
    "",
    sizeof (AuthenticationRsp),
    1,
    authentication_rsp__field_descriptors,
    authentication_rsp__field_indices_by_name,
    1, authentication_rsp__number_ranges,
    (ProtobufCMessageInit) authentication_rsp__init,
    NULL, NULL, NULL            /* reserved[123] */
};

static const ProtobufCFieldDescriptor logout_req__field_descriptors[1] = {
    {
     "user_name",
     1,
     PROTOBUF_C_LABEL_REQUIRED,
     PROTOBUF_C_TYPE_STRING,
     0,                         /* quantifier_offset */
     offsetof (LogoutReq, user_name),
     NULL,
     NULL,
     0,                         /* flags */
     0, NULL, NULL              /* reserved1,reserved2, etc */
     },
};

static const unsigned logout_req__field_indices_by_name[] = {
    0,                          /* field[0] = user_name */
};

static const ProtobufCIntRange logout_req__number_ranges[1 + 1] = {
    {1, 0},
    {0, 1}
};

const ProtobufCMessageDescriptor logout_req__descriptor = {
    PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
    "LogoutReq",
    "LogoutReq",
    "LogoutReq",
    "",
    sizeof (LogoutReq),
    1,
    logout_req__field_descriptors,
    logout_req__field_indices_by_name,
    1, logout_req__number_ranges,
    (ProtobufCMessageInit) logout_req__init,
    NULL, NULL, NULL            /* reserved[123] */
};

static const ProtobufCFieldDescriptor logout_rsp__field_descriptors[1] = {
    {
     "result",
     1,
     PROTOBUF_C_LABEL_REQUIRED,
     PROTOBUF_C_TYPE_INT32,
     0,                         /* quantifier_offset */
     offsetof (LogoutRsp, result),
     NULL,
     NULL,
     0,                         /* flags */
     0, NULL, NULL              /* reserved1,reserved2, etc */
     },
};

static const unsigned logout_rsp__field_indices_by_name[] = {
    0,                          /* field[0] = result */
};

static const ProtobufCIntRange logout_rsp__number_ranges[1 + 1] = {
    {1, 0},
    {0, 1}
};

const ProtobufCMessageDescriptor logout_rsp__descriptor = {
    PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
    "LogoutRsp",
    "LogoutRsp",
    "LogoutRsp",
    "",
    sizeof (LogoutRsp),
    1,
    logout_rsp__field_descriptors,
    logout_rsp__field_indices_by_name,
    1, logout_rsp__number_ranges,
    (ProtobufCMessageInit) logout_rsp__init,
    NULL, NULL, NULL            /* reserved[123] */
};

static const ProtobufCFieldDescriptor member_recd__field_descriptors[2] = {
    {
     "friend_name",
     1,
     PROTOBUF_C_LABEL_REQUIRED,
     PROTOBUF_C_TYPE_STRING,
     0,                         /* quantifier_offset */
     offsetof (MemberRecd, friend_name),
     NULL,
     NULL,
     0,                         /* flags */
     0, NULL, NULL              /* reserved1,reserved2, etc */
     },
    {
     "status",
     2,
     PROTOBUF_C_LABEL_REQUIRED,
     PROTOBUF_C_TYPE_INT32,
     0,                         /* quantifier_offset */
     offsetof (MemberRecd, status),
     NULL,
     NULL,
     0,                         /* flags */
     0, NULL, NULL              /* reserved1,reserved2, etc */
     },
};

static const unsigned member_recd__field_indices_by_name[] = {
    0,                          /* field[0] = friend_name */
    1,                          /* field[1] = status */
};

static const ProtobufCIntRange member_recd__number_ranges[1 + 1] = {
    {1, 0},
    {0, 2}
};

const ProtobufCMessageDescriptor member_recd__descriptor = {
    PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
    "MemberRecd",
    "MemberRecd",
    "MemberRecd",
    "",
    sizeof (MemberRecd),
    2,
    member_recd__field_descriptors,
    member_recd__field_indices_by_name,
    1, member_recd__number_ranges,
    (ProtobufCMessageInit) member_recd__init,
    NULL, NULL, NULL            /* reserved[123] */
};

static const ProtobufCFieldDescriptor notify_friends_rsp__field_descriptors[1] = {
    {
     "user",
     1,
     PROTOBUF_C_LABEL_REQUIRED,
     PROTOBUF_C_TYPE_MESSAGE,
     0,                         /* quantifier_offset */
     offsetof (NotifyFriendsRsp, user),
     &member_recd__descriptor,
     NULL,
     0,                         /* flags */
     0, NULL, NULL              /* reserved1,reserved2, etc */
     },
};

static const unsigned notify_friends_rsp__field_indices_by_name[] = {
    0,                          /* field[0] = user */
};

static const ProtobufCIntRange notify_friends_rsp__number_ranges[1 + 1] = {
    {1, 0},
    {0, 1}
};

const ProtobufCMessageDescriptor notify_friends_rsp__descriptor = {
    PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
    "NotifyFriendsRsp",
    "NotifyFriendsRsp",
    "NotifyFriendsRsp",
    "",
    sizeof (NotifyFriendsRsp),
    1,
    notify_friends_rsp__field_descriptors,
    notify_friends_rsp__field_indices_by_name,
    1, notify_friends_rsp__number_ranges,
    (ProtobufCMessageInit) notify_friends_rsp__init,
    NULL, NULL, NULL            /* reserved[123] */
};

static const ProtobufCFieldDescriptor friend_list_rsp__field_descriptors[1] = {
    {
     "friend_list",
     1,
     PROTOBUF_C_LABEL_REPEATED,
     PROTOBUF_C_TYPE_MESSAGE,
     offsetof (FriendListRsp, n_friend_list),
     offsetof (FriendListRsp, friend_list),
     &member_recd__descriptor,
     NULL,
     0,                         /* flags */
     0, NULL, NULL              /* reserved1,reserved2, etc */
     },
};

static const unsigned friend_list_rsp__field_indices_by_name[] = {
    0,                          /* field[0] = friend_list */
};

static const ProtobufCIntRange friend_list_rsp__number_ranges[1 + 1] = {
    {1, 0},
    {0, 1}
};

const ProtobufCMessageDescriptor friend_list_rsp__descriptor = {
    PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
    "FriendListRsp",
    "FriendListRsp",
    "FriendListRsp",
    "",
    sizeof (FriendListRsp),
    1,
    friend_list_rsp__field_descriptors,
    friend_list_rsp__field_indices_by_name,
    1, friend_list_rsp__number_ranges,
    (ProtobufCMessageInit) friend_list_rsp__init,
    NULL, NULL, NULL            /* reserved[123] */
};

static const ProtobufCFieldDescriptor register_req__field_descriptors[11] = {
    {
     "user_name",
     1,
     PROTOBUF_C_LABEL_REQUIRED,
     PROTOBUF_C_TYPE_STRING,
     0,                         /* quantifier_offset */
     offsetof (RegisterReq, user_name),
     NULL,
     NULL,
     0,                         /* flags */
     0, NULL, NULL              /* reserved1,reserved2, etc */
     },
    {
     "password",
     2,
     PROTOBUF_C_LABEL_REQUIRED,
     PROTOBUF_C_TYPE_STRING,
     0,                         /* quantifier_offset */
     offsetof (RegisterReq, password),
     NULL,
     NULL,
     0,                         /* flags */
     0, NULL, NULL              /* reserved1,reserved2, etc */
     },
    {
     "s_add1",
     3,
     PROTOBUF_C_LABEL_OPTIONAL,
     PROTOBUF_C_TYPE_STRING,
     0,                         /* quantifier_offset */
     offsetof (RegisterReq, s_add1),
     NULL,
     NULL,
     0,                         /* flags */
     0, NULL, NULL              /* reserved1,reserved2, etc */
     },
    {
     "s_add2",
     4,
     PROTOBUF_C_LABEL_OPTIONAL,
     PROTOBUF_C_TYPE_STRING,
     0,                         /* quantifier_offset */
     offsetof (RegisterReq, s_add2),
     NULL,
     NULL,
     0,                         /* flags */
     0, NULL, NULL              /* reserved1,reserved2, etc */
     },
    {
     "s_phone1",
     5,
     PROTOBUF_C_LABEL_OPTIONAL,
     PROTOBUF_C_TYPE_STRING,
     0,                         /* quantifier_offset */
     offsetof (RegisterReq, s_phone1),
     NULL,
     NULL,
     0,                         /* flags */
     0, NULL, NULL              /* reserved1,reserved2, etc */
     },
    {
     "s_phone2",
     6,
     PROTOBUF_C_LABEL_OPTIONAL,
     PROTOBUF_C_TYPE_STRING,
     0,                         /* quantifier_offset */
     offsetof (RegisterReq, s_phone2),
     NULL,
     NULL,
     0,                         /* flags */
     0, NULL, NULL              /* reserved1,reserved2, etc */
     },
    {
     "s_email1",
     7,
     PROTOBUF_C_LABEL_OPTIONAL,
     PROTOBUF_C_TYPE_STRING,
     0,                         /* quantifier_offset */
     offsetof (RegisterReq, s_email1),
     NULL,
     NULL,
     0,                         /* flags */
     0, NULL, NULL              /* reserved1,reserved2, etc */
     },
    {
     "s_email2",
     8,
     PROTOBUF_C_LABEL_OPTIONAL,
     PROTOBUF_C_TYPE_STRING,
     0,                         /* quantifier_offset */
     offsetof (RegisterReq, s_email2),
     NULL,
     NULL,
     0,                         /* flags */
     0, NULL, NULL              /* reserved1,reserved2, etc */
     },
    {
     "s_pin",
     9,
     PROTOBUF_C_LABEL_OPTIONAL,
     PROTOBUF_C_TYPE_STRING,
     0,                         /* quantifier_offset */
     offsetof (RegisterReq, s_pin),
     NULL,
     NULL,
     0,                         /* flags */
     0, NULL, NULL              /* reserved1,reserved2, etc */
     },
    {
     "s_city",
     10,
     PROTOBUF_C_LABEL_OPTIONAL,
     PROTOBUF_C_TYPE_STRING,
     0,                         /* quantifier_offset */
     offsetof (RegisterReq, s_city),
     NULL,
     NULL,
     0,                         /* flags */
     0, NULL, NULL              /* reserved1,reserved2, etc */
     },
    {
     "s_professtion",
     11,
     PROTOBUF_C_LABEL_OPTIONAL,
     PROTOBUF_C_TYPE_STRING,
     0,                         /* quantifier_offset */
     offsetof (RegisterReq, s_professtion),
     NULL,
     NULL,
     0,                         /* flags */
     0, NULL, NULL              /* reserved1,reserved2, etc */
     },
};

static const unsigned register_req__field_indices_by_name[] = {
    1,                          /* field[1] = password */
    2,                          /* field[2] = s_add1 */
    3,                          /* field[3] = s_add2 */
    9,                          /* field[9] = s_city */
    6,                          /* field[6] = s_email1 */
    7,                          /* field[7] = s_email2 */
    4,                          /* field[4] = s_phone1 */
    5,                          /* field[5] = s_phone2 */
    8,                          /* field[8] = s_pin */
    10,                         /* field[10] = s_professtion */
    0,                          /* field[0] = user_name */
};

static const ProtobufCIntRange register_req__number_ranges[1 + 1] = {
    {1, 0},
    {0, 11}
};

const ProtobufCMessageDescriptor register_req__descriptor = {
    PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
    "RegisterReq",
    "RegisterReq",
    "RegisterReq",
    "",
    sizeof (RegisterReq),
    11,
    register_req__field_descriptors,
    register_req__field_indices_by_name,
    1, register_req__number_ranges,
    (ProtobufCMessageInit) register_req__init,
    NULL, NULL, NULL            /* reserved[123] */
};

static const ProtobufCFieldDescriptor register_rsp__field_descriptors[1] = {
    {
     "result",
     1,
     PROTOBUF_C_LABEL_REQUIRED,
     PROTOBUF_C_TYPE_INT32,
     0,                         /* quantifier_offset */
     offsetof (RegisterRsp, result),
     NULL,
     NULL,
     0,                         /* flags */
     0, NULL, NULL              /* reserved1,reserved2, etc */
     },
};

static const unsigned register_rsp__field_indices_by_name[] = {
    0,                          /* field[0] = result */
};

static const ProtobufCIntRange register_rsp__number_ranges[1 + 1] = {
    {1, 0},
    {0, 1}
};

const ProtobufCMessageDescriptor register_rsp__descriptor = {
    PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
    "RegisterRsp",
    "RegisterRsp",
    "RegisterRsp",
    "",
    sizeof (RegisterRsp),
    1,
    register_rsp__field_descriptors,
    register_rsp__field_indices_by_name,
    1, register_rsp__number_ranges,
    (ProtobufCMessageInit) register_rsp__init,
    NULL, NULL, NULL            /* reserved[123] */
};

static const ProtobufCFieldDescriptor add_friend_req__field_descriptors[2] = {
    {
     "user_name",
     1,
     PROTOBUF_C_LABEL_REQUIRED,
     PROTOBUF_C_TYPE_STRING,
     0,                         /* quantifier_offset */
     offsetof (AddFriendReq, user_name),
     NULL,
     NULL,
     0,                         /* flags */
     0, NULL, NULL              /* reserved1,reserved2, etc */
     },
    {
     "friend_name",
     2,
     PROTOBUF_C_LABEL_REQUIRED,
     PROTOBUF_C_TYPE_STRING,
     0,                         /* quantifier_offset */
     offsetof (AddFriendReq, friend_name),
     NULL,
     NULL,
     0,                         /* flags */
     0, NULL, NULL              /* reserved1,reserved2, etc */
     },
};

static const unsigned add_friend_req__field_indices_by_name[] = {
    1,                          /* field[1] = friend_name */
    0,                          /* field[0] = user_name */
};

static const ProtobufCIntRange add_friend_req__number_ranges[1 + 1] = {
    {1, 0},
    {0, 2}
};

const ProtobufCMessageDescriptor add_friend_req__descriptor = {
    PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
    "AddFriendReq",
    "AddFriendReq",
    "AddFriendReq",
    "",
    sizeof (AddFriendReq),
    2,
    add_friend_req__field_descriptors,
    add_friend_req__field_indices_by_name,
    1, add_friend_req__number_ranges,
    (ProtobufCMessageInit) add_friend_req__init,
    NULL, NULL, NULL            /* reserved[123] */
};

static const ProtobufCFieldDescriptor friend_status_rsp__field_descriptors[3] = {
    {
     "user_name",
     1,
     PROTOBUF_C_LABEL_REQUIRED,
     PROTOBUF_C_TYPE_STRING,
     0,                         /* quantifier_offset */
     offsetof (FriendStatusRsp, user_name),
     NULL,
     NULL,
     0,                         /* flags */
     0, NULL, NULL              /* reserved1,reserved2, etc */
     },
    {
     "friend_name",
     2,
     PROTOBUF_C_LABEL_REQUIRED,
     PROTOBUF_C_TYPE_STRING,
     0,                         /* quantifier_offset */
     offsetof (FriendStatusRsp, friend_name),
     NULL,
     NULL,
     0,                         /* flags */
     0, NULL, NULL              /* reserved1,reserved2, etc */
     },
    {
     "status",
     3,
     PROTOBUF_C_LABEL_REQUIRED,
     PROTOBUF_C_TYPE_INT32,
     0,                         /* quantifier_offset */
     offsetof (FriendStatusRsp, status),
     NULL,
     NULL,
     0,                         /* flags */
     0, NULL, NULL              /* reserved1,reserved2, etc */
     },
};

static const unsigned friend_status_rsp__field_indices_by_name[] = {
    1,                          /* field[1] = friend_name */
    2,                          /* field[2] = status */
    0,                          /* field[0] = user_name */
};

static const ProtobufCIntRange friend_status_rsp__number_ranges[1 + 1] = {
    {1, 0},
    {0, 3}
};

const ProtobufCMessageDescriptor friend_status_rsp__descriptor = {
    PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
    "FriendStatusRsp",
    "FriendStatusRsp",
    "FriendStatusRsp",
    "",
    sizeof (FriendStatusRsp),
    3,
    friend_status_rsp__field_descriptors,
    friend_status_rsp__field_indices_by_name,
    1, friend_status_rsp__number_ranges,
    (ProtobufCMessageInit) friend_status_rsp__init,
    NULL, NULL, NULL            /* reserved[123] */
};

static const ProtobufCFieldDescriptor acceptance_friend_req__field_descriptors[3] = {
    {
     "user_name",
     1,
     PROTOBUF_C_LABEL_REQUIRED,
     PROTOBUF_C_TYPE_STRING,
     0,                         /* quantifier_offset */
     offsetof (AcceptanceFriendReq, user_name),
     NULL,
     NULL,
     0,                         /* flags */
     0, NULL, NULL              /* reserved1,reserved2, etc */
     },
    {
     "friend_name",
     2,
     PROTOBUF_C_LABEL_REQUIRED,
     PROTOBUF_C_TYPE_STRING,
     0,                         /* quantifier_offset */
     offsetof (AcceptanceFriendReq, friend_name),
     NULL,
     NULL,
     0,                         /* flags */
     0, NULL, NULL              /* reserved1,reserved2, etc */
     },
    {
     "status",
     3,
     PROTOBUF_C_LABEL_REQUIRED,
     PROTOBUF_C_TYPE_INT32,
     0,                         /* quantifier_offset */
     offsetof (AcceptanceFriendReq, status),
     NULL,
     NULL,
     0,                         /* flags */
     0, NULL, NULL              /* reserved1,reserved2, etc */
     },
};

static const unsigned acceptance_friend_req__field_indices_by_name[] = {
    1,                          /* field[1] = friend_name */
    2,                          /* field[2] = status */
    0,                          /* field[0] = user_name */
};

static const ProtobufCIntRange acceptance_friend_req__number_ranges[1 + 1] = {
    {1, 0},
    {0, 3}
};

const ProtobufCMessageDescriptor acceptance_friend_req__descriptor = {
    PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
    "AcceptanceFriendReq",
    "AcceptanceFriendReq",
    "AcceptanceFriendReq",
    "",
    sizeof (AcceptanceFriendReq),
    3,
    acceptance_friend_req__field_descriptors,
    acceptance_friend_req__field_indices_by_name,
    1, acceptance_friend_req__number_ranges,
    (ProtobufCMessageInit) acceptance_friend_req__init,
    NULL, NULL, NULL            /* reserved[123] */
};

static const ProtobufCFieldDescriptor delete_friend_req__field_descriptors[2] = {
    {
     "user_name",
     1,
     PROTOBUF_C_LABEL_REQUIRED,
     PROTOBUF_C_TYPE_STRING,
     0,                         /* quantifier_offset */
     offsetof (DeleteFriendReq, user_name),
     NULL,
     NULL,
     0,                         /* flags */
     0, NULL, NULL              /* reserved1,reserved2, etc */
     },
    {
     "friend_name",
     2,
     PROTOBUF_C_LABEL_REQUIRED,
     PROTOBUF_C_TYPE_STRING,
     0,                         /* quantifier_offset */
     offsetof (DeleteFriendReq, friend_name),
     NULL,
     NULL,
     0,                         /* flags */
     0, NULL, NULL              /* reserved1,reserved2, etc */
     },
};

static const unsigned delete_friend_req__field_indices_by_name[] = {
    1,                          /* field[1] = friend_name */
    0,                          /* field[0] = user_name */
};

static const ProtobufCIntRange delete_friend_req__number_ranges[1 + 1] = {
    {1, 0},
    {0, 2}
};

const ProtobufCMessageDescriptor delete_friend_req__descriptor = {
    PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
    "DeleteFriendReq",
    "DeleteFriendReq",
    "DeleteFriendReq",
    "",
    sizeof (DeleteFriendReq),
    2,
    delete_friend_req__field_descriptors,
    delete_friend_req__field_indices_by_name,
    1, delete_friend_req__number_ranges,
    (ProtobufCMessageInit) delete_friend_req__init,
    NULL, NULL, NULL            /* reserved[123] */
};

static const ProtobufCFieldDescriptor delete_friend_rsp__field_descriptors[3] = {
    {
     "user_name",
     1,
     PROTOBUF_C_LABEL_REQUIRED,
     PROTOBUF_C_TYPE_STRING,
     0,                         /* quantifier_offset */
     offsetof (DeleteFriendRsp, user_name),
     NULL,
     NULL,
     0,                         /* flags */
     0, NULL, NULL              /* reserved1,reserved2, etc */
     },
    {
     "friend_name",
     2,
     PROTOBUF_C_LABEL_REQUIRED,
     PROTOBUF_C_TYPE_STRING,
     0,                         /* quantifier_offset */
     offsetof (DeleteFriendRsp, friend_name),
     NULL,
     NULL,
     0,                         /* flags */
     0, NULL, NULL              /* reserved1,reserved2, etc */
     },
    {
     "status",
     3,
     PROTOBUF_C_LABEL_REQUIRED,
     PROTOBUF_C_TYPE_INT32,
     0,                         /* quantifier_offset */
     offsetof (DeleteFriendRsp, status),
     NULL,
     NULL,
     0,                         /* flags */
     0, NULL, NULL              /* reserved1,reserved2, etc */
     },
};

static const unsigned delete_friend_rsp__field_indices_by_name[] = {
    1,                          /* field[1] = friend_name */
    2,                          /* field[2] = status */
    0,                          /* field[0] = user_name */
};

static const ProtobufCIntRange delete_friend_rsp__number_ranges[1 + 1] = {
    {1, 0},
    {0, 3}
};

const ProtobufCMessageDescriptor delete_friend_rsp__descriptor = {
    PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
    "DeleteFriendRsp",
    "DeleteFriendRsp",
    "DeleteFriendRsp",
    "",
    sizeof (DeleteFriendRsp),
    3,
    delete_friend_rsp__field_descriptors,
    delete_friend_rsp__field_indices_by_name,
    1, delete_friend_rsp__number_ranges,
    (ProtobufCMessageInit) delete_friend_rsp__init,
    NULL, NULL, NULL            /* reserved[123] */
};

static const ProtobufCFieldDescriptor msg_req_rsp__field_descriptors[3] = {
    {
     "target",
     1,
     PROTOBUF_C_LABEL_REQUIRED,
     PROTOBUF_C_TYPE_STRING,
     0,                         /* quantifier_offset */
     offsetof (MsgReqRsp, target),
     NULL,
     NULL,
     0,                         /* flags */
     0, NULL, NULL              /* reserved1,reserved2, etc */
     },
    {
     "source",
     2,
     PROTOBUF_C_LABEL_REQUIRED,
     PROTOBUF_C_TYPE_STRING,
     0,                         /* quantifier_offset */
     offsetof (MsgReqRsp, source),
     NULL,
     NULL,
     0,                         /* flags */
     0, NULL, NULL              /* reserved1,reserved2, etc */
     },
    {
     "text",
     3,
     PROTOBUF_C_LABEL_REQUIRED,
     PROTOBUF_C_TYPE_STRING,
     0,                         /* quantifier_offset */
     offsetof (MsgReqRsp, text),
     NULL,
     NULL,
     0,                         /* flags */
     0, NULL, NULL              /* reserved1,reserved2, etc */
     },
};

static const unsigned msg_req_rsp__field_indices_by_name[] = {
    1,                          /* field[1] = source */
    0,                          /* field[0] = target */
    2,                          /* field[2] = text */
};

static const ProtobufCIntRange msg_req_rsp__number_ranges[1 + 1] = {
    {1, 0},
    {0, 3}
};

const ProtobufCMessageDescriptor msg_req_rsp__descriptor = {
    PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
    "MsgReqRsp",
    "MsgReqRsp",
    "MsgReqRsp",
    "",
    sizeof (MsgReqRsp),
    3,
    msg_req_rsp__field_descriptors,
    msg_req_rsp__field_indices_by_name,
    1, msg_req_rsp__number_ranges,
    (ProtobufCMessageInit) msg_req_rsp__init,
    NULL, NULL, NULL            /* reserved[123] */
};

static const ProtobufCFieldDescriptor unregister_req__field_descriptors[1] = {
    {
     "user_name",
     1,
     PROTOBUF_C_LABEL_REQUIRED,
     PROTOBUF_C_TYPE_STRING,
     0,                         /* quantifier_offset */
     offsetof (UnregisterReq, user_name),
     NULL,
     NULL,
     0,                         /* flags */
     0, NULL, NULL              /* reserved1,reserved2, etc */
     },
};

static const unsigned unregister_req__field_indices_by_name[] = {
    0,                          /* field[0] = user_name */
};

static const ProtobufCIntRange unregister_req__number_ranges[1 + 1] = {
    {1, 0},
    {0, 1}
};

const ProtobufCMessageDescriptor unregister_req__descriptor = {
    PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
    "UnregisterReq",
    "UnregisterReq",
    "UnregisterReq",
    "",
    sizeof (UnregisterReq),
    1,
    unregister_req__field_descriptors,
    unregister_req__field_indices_by_name,
    1, unregister_req__number_ranges,
    (ProtobufCMessageInit) unregister_req__init,
    NULL, NULL, NULL            /* reserved[123] */
};

static const ProtobufCFieldDescriptor unregister_rsp__field_descriptors[1] = {
    {
     "unreg",
     1,
     PROTOBUF_C_LABEL_REQUIRED,
     PROTOBUF_C_TYPE_INT32,
     0,                         /* quantifier_offset */
     offsetof (UnregisterRsp, unreg),
     NULL,
     NULL,
     0,                         /* flags */
     0, NULL, NULL              /* reserved1,reserved2, etc */
     },
};

static const unsigned unregister_rsp__field_indices_by_name[] = {
    0,                          /* field[0] = unreg */
};

static const ProtobufCIntRange unregister_rsp__number_ranges[1 + 1] = {
    {1, 0},
    {0, 1}
};

const ProtobufCMessageDescriptor unregister_rsp__descriptor = {
    PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
    "UnregisterRsp",
    "UnregisterRsp",
    "UnregisterRsp",
    "",
    sizeof (UnregisterRsp),
    1,
    unregister_rsp__field_descriptors,
    unregister_rsp__field_indices_by_name,
    1, unregister_rsp__number_ranges,
    (ProtobufCMessageInit) unregister_rsp__init,
    NULL, NULL, NULL            /* reserved[123] */
};
