######################################################################
# Automatically generated by qmake (2.01a) Fri Jul 31 12:17:02 2015
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += comp.h
SOURCES += comp.cpp main.cpp
