CC= gcc-5
CFLAGS= -Wall -Wextra -Wformat -std=c99 -g

all:

list:
	$(CC) $(CFLAGS) -o test listtest.c ../src/list.c

sds:
	$(CC) $(CFLAGS) -o test sdstest.c ../src/sds.c

table:
	$(CC) $(CFLAGS) -o test tabletest.c ../src/table.c
