#!/bin/sh
# Use this script to re-create configure. Requires the following auto-tools,
# autoconf        >= 2.59
# automake        >= 1.10
# libtool         >= 1.4
if (glibtoolize -f -c 2>/dev/null || libtoolize -f -c) && aclocal -I config && autoheader && automake --foreign --add-missing --copy && autoconf 
then
        echo "Success bootstrapping libmonit"
else
        echo "Failed bootstrapping libmonit"
        exit 1;
fi
exit 0;
