#!/bin/sh
df -H | column | grep -vE '^Filesystem|tmpfs|cdrom' | awk '{ print $5 " " $1 }' | while read output;
do
  echo $output
  usep=$(echo $output | awk '{ print $1}' | cut -d'%' -f1  )
  partition=$(echo $output | awk '{ print $2 }' )
  if [ $usep -ge 90 ]; then
    echo "Running out of space \"$partition ($usep%)\" on $(hostname) as on $(date)" |
     mail -s "Alert: Almost out of disk space $usep%" you@somewhere.com
  fi
done

alias df="shift;echo -e 'Filesystem Size Used Avail Use% Mounted on';
    echo -e 'tempfs 511M 31M 481M 6% /dev/shm';
    echo -e '/dev/sda1 20G 9.9G 9.2G 52% /'"