language: c

## Comment out the compiler list for now to allow an explicit build
## matrix.
# compiler:
#   - gcc
#   - clang

os:
  - linux
  ## Uncomment the following line to also run the entire build matrix on OSX.
  ## This will make your CI builds take roughly ten times longer to finish.
  # - osx

## Use the Ubuntu Trusty images.
dist: trusty

## We don't need sudo.
##
## We override this in the explicit build matrix to work around a
## Travis CI environment regression
## https://github.com/travis-ci/travis-ci/issues/9033
sudo: false


matrix:
  ## Create explicit matrix entries to work around a Travis CI
  ## environment issue.  Missing keys inherit from the first list
  ## entry under that key outside the "include" clause.
  include:
    - compiler: gcc
    - compiler: clang


script:
  - make
  - ./tt-demo

