######################################################################
# Automatically generated by qmake (2.01a) Fri Jul 31 14:38:40 2015
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += chinese.cpp
