#!/bin/bash

. my_functions

test_is_password_incorrect()
{
    assertEquals `is_password welcome01` 0
}

test_is_password_correct()
{
    assertEquals `is_password iloverichel` 1
}

# load shunit2
. ../shunit2
