#!/bin/bash
### ShellCheck (http://www.shellcheck.net/)
#  Not following: ./test_helper was not specified as input (see shellcheck -x)
#   shellcheck disable=SC1091
# Double quote to prevent globbing and word splitting
#   shellcheck disable=SC2086

oneTimeSetUp() {
  . "./test_helper"
  status=""
  output=""

  if [ -n "${SLOTD_DEBUG}" ]; then
    SLOTD="slotd -r 2000 -d 1 "
  else
    SLOTD="slotd -r 2000 "
  fi
}

oneTimeTearDown() {
  :
}

setUp() {
  :
}

tearDown() {
  :
}

suite()
{
  source slot_cmd
  source slot_common
  source slot_lms_ilm
  source slot_lms_gdm
  source slot_lms_tpwu
}

# load shunit2
. ./shunit2