#!/bin/bash

. my_functions

is_a_yes()
{
    assertEquals $(is_a a) 1
}

is_a_no()
{
    assertEquals $(is_a x) 0
}

is_a_contaions(){
    assertContains "xxx" "xxx"
}

suite_addTest is_a_yes
suite_addTest is_a_no
suite_addTest is_a_contaions
