#!/bin/bash

# Determines if its single the argument equals an 'a'
# @param $1 argument to be measured to be 'a'
# @return 1 if true, 0 otherwise
function is_a()
{
  if [[ $1 == 'a' ]]; then
    echo "1"
  else
    echo "0"
  fi
}

# Determines if its single the argument equals an 'b'
# @param $1 argument to be measured to be 'b'
# @return 1 if true, 0 otherwise
function is_b()
{
  if [[ $1 == 'b' ]]; then
    echo "1"
  else
    echo "0"
  fi
}