#!/bin/bash

. my_functions

echo "Please enter an 'a' and a 'b', seperated by a space"
read first second

if [[ `is_a $first` == 1 ]]; then

  if [[ `is_b $second` == 1 ]]; then
    echo "Welcome master"
  else
    echo "Incorrect password"
  fi

else
  echo "Incorrect password"
fi
