#line 2 "fb2-5.c"

#line 4 "fb2-5.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5
#define YY_FLEX_SUBMINOR_VERSION 35
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;
#endif /* ! C99 */

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart(yyin  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#define YY_BUF_SIZE 16384
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    /* Note: We specifically omit the test for yy_rule_can_match_eol because it requires
     *       access to the local variable yy_act. Since yyless() is a macro, it would break
     *       existing scanners that call yyless() from OUTSIDE yylex. 
     *       One obvious solution it to make yy_act a global. I tried that, and saw
     *       a 5% performance hit in a non-yylineno scanner, because yy_act is
     *       normally declared as a register variable-- so it is not worth it.
     */
    #define  YY_LESS_LINENO(n) \
            do { \
                int yyl;\
                for ( yyl = n; yyl < yyleng; ++yyl )\
                    if ( yytext[yyl] == '\n' )\
                        --yylineno;\
            }while(0)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = 0; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart (FILE *input_file  );
void yy_switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer (FILE *file,int size  );
void yy_delete_buffer (YY_BUFFER_STATE b  );
void yy_flush_buffer (YY_BUFFER_STATE b  );
void yypush_buffer_state (YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state (void );

static void yyensure_buffer_stack (void );
static void yy_load_buffer_state (void );
static void yy_init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER yy_flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE yy_scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes (yyconst char *bytes,int len  );

void *yyalloc (yy_size_t  );
void *yyrealloc (void *,yy_size_t  );
void yyfree (void *  );

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define yywrap(n) 1
#define YY_SKIP_YYWRAP

typedef unsigned char YY_CHAR;

FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;

typedef int yy_state_type;

extern int yylineno;

int yylineno = 1;

extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
static void yy_fatal_error (yyconst char msg[]  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 70
#define YY_END_OF_BUFFER 71
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[405] =
    {   0,
        0,    0,    0,    0,    0,    0,   71,   69,   59,   59,
       52,   69,   56,   53,   52,   69,   51,   52,   52,   56,
       52,   51,   53,   42,   43,   54,   50,   53,   55,   53,
       54,   58,   58,   69,   53,   58,   58,   58,   58,   58,
       58,   58,   58,   58,   58,   58,   58,   58,   58,   58,
       58,   50,   53,   52,   56,    3,    3,    3,   67,   68,
       59,   53,    0,    0,    0,   56,    0,    0,    0,    0,
       57,   55,   57,    0,    0,   52,   51,    0,   45,    1,
        0,   45,   42,    0,    0,   42,   42,    0,   42,   43,
       43,   43,   43,   50,   53,   53,   58,    0,    0,   60,

        0,    0,    0,   58,   58,   58,   58,   58,   58,   58,
       58,   58,   33,   58,   58,   58,   58,   58,   58,   37,
       58,   58,   58,   58,   58,   58,   58,   58,   58,   58,
       58,    0,    0,    0,    3,    3,    2,    3,   67,   49,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
       48,    0,    0,    0,    0,   54,    0,   45,    0,    4,
        0,   46,   42,   42,   42,   42,    0,   44,   43,   43,
       43,   43,    0,    0,    0,    0,    0,   58,   58,   58,
       58,   58,   58,   58,   58,   58,   58,   58,   58,   58,
       58,   35,   58,   58,   16,   58,   58,   58,   58,   58,

       58,   58,   58,   58,   58,   58,   58,   58,   58,   58,
       58,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,   61,    0,    0,    0,    0,    0,    0,   45,   46,
       42,    0,    0,   44,    0,   44,   44,   43,    0,    0,
        0,    0,   58,   58,   58,    8,   58,   30,    9,   58,
       58,   58,   58,   34,   12,   58,   58,   36,   58,   17,
       58,   58,   58,   58,   58,   58,   58,   58,   58,   58,
       58,   58,   27,   58,   58,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,   44,   44,
        0,   47,   44,   44,    0,    0,    0,    0,    5,   58,

       58,   29,   10,   58,   58,   58,   58,   14,   58,   58,
       58,   58,   20,   58,   58,   58,   58,   58,   58,   25,
       58,   58,   41,    0,    0,    0,    0,    0,   62,    0,
        0,   65,    0,    0,   47,   44,    0,    0,    0,   58,
       58,   58,   58,   58,   11,   13,   15,   58,   58,   38,
       21,   39,   22,   23,   40,   58,   58,   58,    0,    0,
        0,    0,    0,   63,    0,    0,    0,    0,   58,   58,
       58,   32,   58,   58,   24,   58,   58,    0,    0,    0,
       64,    0,    0,    0,    6,   58,   31,   18,   19,   26,
       28,    0,    0,    0,    0,    0,   58,    0,   66,    0,

        0,    0,    7,    0
    } ;

static yyconst flex_int32_t yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    4,    5,    6,    7,    1,    8,    9,   10,   11,
       12,   13,   14,   15,   16,   17,   18,   19,   20,   20,
       20,   20,   20,   20,   20,   21,   21,   22,   23,   24,
       25,   26,   27,    1,   28,   29,   30,   28,   31,   32,
       33,   33,   34,   33,   33,   35,   33,   33,   33,   36,
       33,   33,   33,   33,   37,   33,   33,   38,   33,   33,
       39,   40,   41,   42,   43,    1,   44,   45,   46,   47,

       48,   49,   50,   51,   52,   33,   53,   54,   55,   56,
       57,   58,   33,   59,   60,   61,   62,   63,   64,   65,
       66,   67,   68,   69,   70,   71,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst flex_int32_t yy_meta[72] =
    {   0,
        1,    1,    1,    1,    1,    2,    1,    1,    1,    3,
        1,    1,    4,    1,    1,    1,    5,    1,    6,    6,
        7,    1,    1,    1,    1,    8,    9,    7,    7,    7,
        7,    7,   10,   10,   10,   10,   11,   11,    1,   11,
        1,    1,   10,    6,    6,    7,    7,    7,    6,   10,
       10,   10,   10,   10,   10,   11,   10,   10,   11,   10,
       11,   11,   11,   10,   11,   10,   10,    1,    1,    1,
        1
    } ;

static yyconst flex_int16_t yy_base[468] =
    {   0,
        0, 1008,   59,   60,   68,   69, 1014, 1016,   74,   77,
      988,  972,   78,   61,   75,  971, 1016,  985,   74, 1016,
       76,   92,   78,  116,  121,  983, 1016,   96,  983,   64,
     1016,  967,   87,  111,  981,   76,   57,   58,  106,  119,
      126,  120,   82,   75,   88,  131,  144,   83,  132,  104,
      146, 1016,  936, 1016,  183,  956,  985,  144,    0, 1016,
      199, 1016,  128,  174,  194, 1016,  954,  150,  952,  948,
      991, 1016, 1016,  179,  190, 1016, 1016,  981,  230, 1016,
      994,  237,  273,  278,  201,  181,  108,  979,  170,  294,
      238,  179,  226, 1016,  970,  969,  953,  176,  952, 1016,

        0,    0,  922,  183,  207,  189,  205,  186,  214,  227,
      220,  247,  219,  242,  243,  261,  213,  277,  263,  950,
      276,  267,  278,  249,  293,  300,  280,  294,  301,  310,
      305,  345,  361,  263,  941,  298, 1016,  940,    0, 1016,
      349,    0,    0,    0,  938,  926,  938,  981,  927,  960,
     1016,  356,    0,    0,    0, 1016,  358, 1016,  978, 1016,
      361,  367,  321, 1016,  945,  925,    0,  356,  333, 1016,
      943,  923,    0,    0,    0,    0,  951,  327,  345,  350,
      363,  361,  358,  364,  367,  382,  372,  371,  384,  385,
      390,  935,  389,  391,  934,  115,  392,  395,  396,  398,

      397,  400,  401,  402,  405,  407,  410,  409,  412,  425,
      414,  917,  926,  454,    0,  489,    0,  919,  922,  917,
      965, 1016,  919,  460,    0,  529,    0,  456,  492, 1016,
     1016,  427,  435,  452,  482,  437,  445, 1016,    0,    0,
        0,    0,  438,  446,  465,  926,  444,  925,  924,  482,
      476,  483,  486,  923,  922,  466,  490,  921,  491,  920,
      311,  504,  512,  492,  514,  515,  516,  524,  539,  441,
      525,  540,  919,  526,  543,  904,  561,    0,    0,    0,
      901,  953,  906,  951,  572,    0,    0,    0,  547, 1016,
      573,  576,  918,  898,    0,    0,    0,    0,  911,  546,

      558,  746,  744,  548,  549,  559,  562,  743,  565,  566,
      574,  575,  741,  443,  579,  576,  577,  581,  589,  740,
      580,  583,  736,  712,    0,    0,  725,  768, 1016,  767,
      761, 1016,    0,    0, 1016, 1016,    0,    0,    0,  718,
      593,  584,  594,  599,  709,  703,  702,  602,  603,  691,
      679,  654,  653,  652,  651,  604,  606,  605,  643,    0,
      641,  686,  684, 1016,    0,  638,    0,    0,  611,  617,
      615,  646,  612,  618,  645,  622,  624,  635,    0,  679,
     1016,    0,    0,    0,  640,  625,  634,  627,  502,  411,
      237,  664,    0,    0,    0,    0,  159,  671, 1016,    0,

        0,    0,   89, 1016,  695,  706,  717,  728,  734,  745,
      756,  766,  776,  787,  794,  796,  798,  800,  802,  804,
      811,  817,  819,  821,  823,  825,  827,  829,  831,  833,
      835,  837,  839,  841,  843,  845,  847,  849,  851,  858,
      869,  875,  877,  879,  881,  883,  885,  887,  889,  896,
      902,  904,  906,  908,  910,  912,  919,  925,  927,  929,
      931,  933,  935,  937,  939,  941,  943
    } ;

static yyconst flex_int16_t yy_def[468] =
    {   0,
      404,    1,  405,  405,  406,  406,  404,  404,  404,  404,
      404,  407,  404,  404,  404,  408,  404,  404,  404,  404,
      404,  404,  404,  404,  404,  404,  404,  404,  404,  404,
      404,  409,  409,  404,  404,  409,  409,  409,  409,  409,
      409,  409,  409,  409,  409,  409,  409,  409,  409,  409,
      409,  404,  404,  404,  404,  410,  404,  410,  411,  404,
      404,  404,  407,  412,  404,  404,  404,  404,  404,  404,
      404,  404,  404,  408,  413,  404,  404,  404,  404,  404,
      414,  404,  404,  404,  404,  404,  404,  415,  404,  404,
      404,  404,  404,  404,  404,  404,  409,  404,  407,  404,

      416,  417,  404,  409,  409,  409,  409,  409,  409,  409,
      409,  409,  409,  409,  409,  409,  409,  409,  409,  409,
      409,  409,  409,  409,  409,  409,  409,  409,  409,  409,
      409,  404,  404,  404,  410,  410,  404,  410,  411,  404,
      407,  418,  419,  420,  404,  404,  404,  421,  404,  404,
      404,  408,  422,  423,  424,  404,  404,  404,  414,  404,
      404,  404,  404,  404,  404,  404,  425,  415,  404,  404,
      404,  404,  426,  427,  428,  429,  404,  409,  409,  409,
      409,  409,  409,  409,  409,  409,  409,  409,  409,  409,
      409,  409,  409,  409,  409,  409,  409,  409,  409,  409,

      409,  409,  409,  409,  409,  409,  409,  409,  409,  409,
      409,  404,  404,  407,  430,  407,  431,  404,  404,  404,
      421,  404,  404,  408,  432,  408,  433,  404,  404,  404,
      404,  425,  425,  404,  404,  404,  404,  404,  434,  435,
      436,  437,  409,  409,  409,  409,  409,  409,  409,  409,
      409,  409,  409,  409,  409,  409,  409,  409,  409,  409,
      409,  409,  409,  409,  409,  409,  409,  409,  409,  409,
      409,  409,  409,  409,  409,  404,  407,  438,  216,  439,
      404,  440,  404,  441,  408,  442,  226,  443,  404,  404,
      404,  404,  404,  404,  444,  445,  446,  447,  409,  409,

      409,  409,  409,  409,  409,  409,  409,  409,  409,  409,
      409,  409,  409,  409,  409,  409,  409,  409,  409,  409,
      409,  409,  409,  404,  448,  449,  404,  440,  404,  450,
      441,  404,  451,  452,  404,  404,  453,  454,  455,  409,
      409,  409,  409,  409,  409,  409,  409,  409,  409,  409,
      409,  409,  409,  409,  409,  409,  409,  409,  404,  456,
      407,  457,  450,  404,  458,  408,  459,  460,  409,  409,
      409,  409,  409,  409,  409,  409,  409,  404,  461,  457,
      404,  462,  463,  464,  409,  409,  409,  409,  409,  409,
      409,  404,  465,  466,  467,  447,  409,  404,  404,  449,

      452,  454,  409,    0,  404,  404,  404,  404,  404,  404,
      404,  404,  404,  404,  404,  404,  404,  404,  404,  404,
      404,  404,  404,  404,  404,  404,  404,  404,  404,  404,
      404,  404,  404,  404,  404,  404,  404,  404,  404,  404,
      404,  404,  404,  404,  404,  404,  404,  404,  404,  404,
      404,  404,  404,  404,  404,  404,  404,  404,  404,  404,
      404,  404,  404,  404,  404,  404,  404
    } ;

static yyconst flex_int16_t yy_nxt[1088] =
    {   0,
        8,    9,   10,    9,   11,   12,   13,   14,   15,   16,
       17,   17,   18,   19,   20,   21,   22,   23,   24,   25,
       25,   26,   27,   28,   29,   30,   31,   32,   32,   32,
       32,   32,   32,   32,   33,   32,   32,   32,   17,   34,
       17,   35,   36,   37,   38,   39,   40,   41,   42,   43,
       32,   44,   32,   45,   32,   32,   32,   32,   46,   47,
       48,   49,   50,   51,   32,   32,   32,   52,   53,   17,
       54,   57,   57,   60,   60,   61,   61,   61,   61,   61,
       61,   65,   71,   62,   66,   72,   73,   76,   62,   96,
       80,   76,   99,   60,   60,   81,   98,   98,   72,   72,

       72,   77,   72,   94,  104,  105,   58,   58,   78,  106,
       79,   79,   79,  100,   98,   98,  108,   73,  107,   95,
       62,   98,   98,  120,   67,   68,   98,   98,   98,   69,
      121,   70,   82,  140,   83,   83,   84,   82,  119,   90,
       90,   90,  165,   98,  122,   98,   85,  101,  128,  109,
       86,   85,   87,   88,   98,   91,  110,   92,   98,   98,
      130,  166,  111,   85,  260,   98,  112,   64,   85,   89,
       98,   98,  102,  117,   93,  113,  118,   87,  123,  114,
       88,  115,   92,   98,  132,   98,  133,  129,  151,   66,
      116,  136,  141,  141,  124,  125,  131,   65,   98,  138,

       61,   61,   61,  146,  126,  147,  164,  127,  152,  152,
      142,  143,  173,  171,  161,  163,  161,  164,   75,  162,
      162,  162,   98,  163,  403,   98,  153,  154,   98,   67,
       68,  164,  172,  182,  134,  144,   70,  174,  143,  178,
       67,   68,  164,  180,   98,   69,   98,   70,   79,   79,
       79,  155,   98,   98,  154,   79,   79,   79,   98,   98,
      157,  158,  170,  179,  158,  181,   98,  157,  158,  191,
      184,  158,  169,  183,  170,  185,   98,  157,  158,  169,
      187,   98,   98,  158,  157,  158,   98,  170,   98,   82,
      158,   83,   83,   84,   82,  186,   84,   84,   84,  170,

       98,  188,   98,   85,  189,  200,   98,   86,   85,   87,
       82,  148,   90,   90,   90,   98,   98,   98,  213,   98,
       85,  190,  196,  193,   85,   85,   89,  197,   91,  194,
       92,  205,   98,   98,   87,  192,  195,  198,  199,   98,
       98,   85,  201,  203,   98,  136,  132,   93,  132,   98,
       98,  206,  207,  138,  140,   92,  211,  164,  204,  202,
      208,  209,  132,  210,  133,  151,   98,  214,  214,  170,
      310,  228,  233,  228,  224,  224,  229,  229,  229,  162,
      162,  162,  164,  243,   98,  162,  162,  162,   64,   98,
      234,  235,  236,  245,  170,   75,  212,   98,  230,  244,

       98,  230,   98,   98,  247,  248,   98,   67,   68,  237,
       98,   98,  134,  235,   70,  230,  253,  236,  254,  246,
      230,   98,  249,   98,   98,  252,  250,  251,   98,   98,
       98,   98,  256,  257,   98,   98,   98,   98,  255,   98,
       98,   98,  259,  261,   98,  258,   98,  266,   98,   98,
       98,   98,  265,   98,  270,  262,  264,  263,  273,  140,
      272,  267,  235,  268,   98,  269,  271,  275,  274,  151,
      235,  293,  277,  277,  229,  229,  229,   98,  285,  285,
       98,  290,   98,   98,  235,   98,  289,  319,  290,  351,
      294,  299,  235,   64,  140,  291,  302,  291,  289,   75,

      292,  292,  292,  300,   98,   98,  290,  279,  279,  279,
      229,  229,  229,  290,  301,   98,  279,  279,  279,  279,
      279,   98,   98,  158,  307,   98,  158,  304,   64,   98,
       98,   98,  279,  279,  279,  279,  279,  279,  151,  306,
      158,   98,  303,   98,  305,  158,  309,  287,  287,  287,
      308,   98,  313,   98,   98,   98,  287,  287,  287,  287,
      287,  314,  311,   98,   98,   98,  140,  316,   75,  317,
      312,  315,  287,  287,  287,  287,  287,  287,   98,   98,
      320,  151,   98,  290,  318,   98,  322,   98,   98,  321,
      323,  292,  292,  292,  292,  292,  292,   98,   98,  341,

       64,   98,  344,  343,   98,   98,  345,  335,  290,  342,
      335,   75,  347,   98,   98,   98,   98,  346,   98,   98,
       98,  353,   98,   98,  335,  349,  348,  352,   98,  335,
      350,  355,   98,   98,  358,  357,  356,  354,   98,  370,
      369,   98,   98,   98,   98,   98,  140,  151,  374,  373,
       98,   98,  375,  376,   98,  371,   98,   98,  377,  372,
      386,   98,  387,   98,   98,  398,   98,  398,  390,  399,
      388,  391,  398,   98,  398,  385,  399,   75,  389,   98,
       64,  381,  392,  397,   98,   98,  364,  399,  381,  378,
       98,   98,   98,   98,  399,   56,   56,   56,   56,   56,

       56,   56,   56,   56,   56,   56,   59,   59,   59,   59,
       59,   59,   59,   59,   59,   59,   59,   63,   98,   63,
       63,   63,   63,   63,   63,   63,   63,   63,   74,   74,
       98,   74,   74,   74,   74,   74,   74,   74,   74,   97,
       97,   98,   98,   97,   97,  135,  135,  135,   98,  135,
      135,  135,  135,  135,  135,  135,  139,   98,  139,  139,
      139,  139,  139,  332,  139,  139,  139,   63,   63,  364,
      329,   63,  362,  359,   63,   98,   63,   74,   74,   98,
       98,   74,   98,   98,   74,   98,   74,  159,  159,  159,
      159,  159,  159,  159,  159,  159,  159,  159,  168,  168,

      168,  175,  175,  176,  176,  215,  215,  216,  216,  217,
      217,  221,  221,  221,  221,  221,  221,  221,  221,  221,
      221,  221,  225,  225,  226,  226,  227,  227,  232,  232,
      239,  239,  240,  240,  241,  241,  242,  242,  278,  278,
      280,  280,  286,  286,  288,  288,  295,  295,  296,  296,
      297,  297,  298,  298,  325,  325,  326,  326,  328,  328,
      328,  328,  328,  328,  328,  328,  328,  328,  328,  331,
      331,  331,  331,  331,  331,  331,  331,  331,  331,  331,
      333,  333,  334,  334,  337,  337,  338,  338,  339,  339,
      340,  340,  360,  360,  361,  361,  363,  363,  363,  363,

      363,  363,  363,  363,  363,  363,  363,  365,  365,  366,
      366,  367,  367,   97,   97,  368,  368,  379,  379,  380,
      380,  380,  380,  380,  380,  380,  380,  380,  380,  380,
      382,  382,  383,  383,  384,  384,  393,  393,  394,  394,
      395,  395,  396,  396,  400,  400,  401,  401,  402,  402,
       98,  336,  336,  332,  330,  329,  327,  324,   98,   98,
       98,   98,   98,   98,   98,   98,  284,  222,  283,  282,
      281,  276,  213,   98,   98,   72,  238,  238,  231,  231,
      160,   73,  223,  222,  220,  219,  218,  136,  136,   98,
      177,   64,   98,   72,   72,  167,  160,  156,  150,  149,

      148,  145,  137,  136,   62,  103,   98,   62,   73,   72,
       75,   64,   62,  404,   55,    7,  404,  404,  404,  404,
      404,  404,  404,  404,  404,  404,  404,  404,  404,  404,
      404,  404,  404,  404,  404,  404,  404,  404,  404,  404,
      404,  404,  404,  404,  404,  404,  404,  404,  404,  404,
      404,  404,  404,  404,  404,  404,  404,  404,  404,  404,
      404,  404,  404,  404,  404,  404,  404,  404,  404,  404,
      404,  404,  404,  404,  404,  404,  404,  404,  404,  404,
      404,  404,  404,  404,  404,  404,  404
    } ;

static yyconst flex_int16_t yy_chk[1088] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    3,    4,    5,    6,    9,    9,    9,   10,   10,
       10,   13,   14,   15,   13,   14,   14,   19,   30,   30,
       23,   21,   33,    5,    6,   23,   37,   38,   19,   15,

       21,   21,   23,   28,   36,   36,    3,    4,   22,   36,
       22,   22,   22,   34,   44,   36,   38,   28,   37,   28,
       28,   43,   48,   44,   13,   13,   33,   45,  403,   13,
       44,   13,   24,   63,   24,   24,   24,   25,   43,   25,
       25,   25,   87,   50,   45,   39,   24,   34,   48,   39,
       24,   25,   24,   24,  196,   25,   39,   25,   40,   42,
       50,   87,   39,   24,  196,   41,   40,   63,   25,   24,
       46,   49,   34,   42,   25,   40,   42,   24,   46,   41,
       24,   41,   25,   47,   55,   51,   55,   49,   74,   55,
       41,   58,   64,   64,   47,   47,   51,   65,  397,   58,

       61,   61,   61,   68,   47,   68,   89,   47,   75,   75,
       64,   64,   98,   92,   85,   86,   85,   86,   74,   85,
       85,   85,  104,   89,  397,  108,   75,   75,  106,   55,
       55,   89,   92,  108,   55,   64,   55,   98,   64,  104,
       65,   65,   86,  106,  107,   65,  105,   65,   79,   79,
       79,   75,  117,  109,   75,   82,   82,   82,  113,  111,
       79,   79,   93,  105,   79,  107,  110,   82,   82,  117,
      110,   82,   91,  109,   91,  111,  391,   79,   79,   93,
      113,  114,  115,   79,   82,   82,  112,   93,  124,   83,
       82,   83,   83,   83,   84,  112,   84,   84,   84,   91,

      116,  114,  119,   83,  115,  124,  122,   83,   84,   83,
       90,  134,   90,   90,   90,  121,  118,  123,  134,  127,
       83,  116,  122,  119,   90,   84,   83,  123,   90,  121,
       90,  127,  125,  128,   83,  118,  121,  123,  123,  126,
      129,   90,  125,  126,  131,  136,  132,   90,  132,  130,
      261,  128,  129,  136,  141,   90,  131,  163,  126,  125,
      129,  130,  133,  130,  133,  152,  178,  141,  141,  169,
      261,  157,  168,  157,  152,  152,  157,  157,  157,  161,
      161,  161,  163,  178,  179,  162,  162,  162,  141,  180,
      168,  168,  168,  180,  169,  152,  132,  183,  162,  179,

      182,  162,  181,  184,  182,  183,  185,  133,  133,  168,
      188,  187,  133,  168,  133,  162,  187,  168,  188,  181,
      162,  186,  184,  189,  190,  186,  185,  185,  193,  191,
      194,  197,  190,  191,  198,  199,  201,  200,  189,  202,
      203,  204,  194,  197,  205,  193,  206,  202,  208,  207,
      390,  209,  201,  211,  206,  198,  200,  199,  209,  214,
      208,  203,  232,  204,  210,  205,  207,  211,  210,  224,
      233,  236,  214,  214,  228,  228,  228,  243,  224,  224,
      270,  237,  314,  247,  232,  244,  234,  270,  234,  314,
      236,  243,  233,  214,  216,  235,  247,  235,  237,  224,

      235,  235,  235,  244,  245,  256,  237,  216,  216,  216,
      229,  229,  229,  234,  245,  251,  216,  216,  216,  216,
      216,  250,  252,  229,  256,  253,  229,  251,  216,  257,
      259,  264,  216,  216,  216,  216,  216,  216,  226,  253,
      229,  389,  250,  262,  252,  229,  259,  226,  226,  226,
      257,  263,  264,  265,  266,  267,  226,  226,  226,  226,
      226,  265,  262,  268,  271,  274,  277,  267,  226,  268,
      263,  266,  226,  226,  226,  226,  226,  226,  269,  272,
      271,  285,  275,  289,  269,  300,  274,  304,  305,  272,
      275,  291,  291,  291,  292,  292,  292,  301,  306,  300,

      277,  307,  305,  304,  309,  310,  306,  292,  289,  301,
      292,  285,  309,  311,  312,  316,  317,  307,  315,  321,
      318,  316,  322,  342,  292,  311,  310,  315,  319,  292,
      312,  318,  341,  343,  322,  321,  319,  317,  344,  342,
      341,  348,  349,  356,  358,  357,  361,  366,  349,  348,
      369,  373,  356,  357,  371,  343,  370,  374,  358,  344,
      370,  376,  371,  377,  386,  392,  388,  392,  376,  392,
      373,  377,  398,  387,  398,  369,  398,  366,  374,  385,
      361,  380,  378,  386,  375,  372,  363,  392,  362,  359,
      355,  354,  353,  352,  398,  405,  405,  405,  405,  405,

      405,  405,  405,  405,  405,  405,  406,  406,  406,  406,
      406,  406,  406,  406,  406,  406,  406,  407,  351,  407,
      407,  407,  407,  407,  407,  407,  407,  407,  408,  408,
      350,  408,  408,  408,  408,  408,  408,  408,  408,  409,
      409,  347,  346,  409,  409,  410,  410,  410,  345,  410,
      410,  410,  410,  410,  410,  410,  411,  340,  411,  411,
      411,  411,  411,  331,  411,  411,  411,  412,  412,  330,
      328,  412,  327,  324,  412,  323,  412,  413,  413,  320,
      313,  413,  308,  303,  413,  302,  413,  414,  414,  414,
      414,  414,  414,  414,  414,  414,  414,  414,  415,  415,

      415,  416,  416,  417,  417,  418,  418,  419,  419,  420,
      420,  421,  421,  421,  421,  421,  421,  421,  421,  421,
      421,  421,  422,  422,  423,  423,  424,  424,  425,  425,
      426,  426,  427,  427,  428,  428,  429,  429,  430,  430,
      431,  431,  432,  432,  433,  433,  434,  434,  435,  435,
      436,  436,  437,  437,  438,  438,  439,  439,  440,  440,
      440,  440,  440,  440,  440,  440,  440,  440,  440,  441,
      441,  441,  441,  441,  441,  441,  441,  441,  441,  441,
      442,  442,  443,  443,  444,  444,  445,  445,  446,  446,
      447,  447,  448,  448,  449,  449,  450,  450,  450,  450,

      450,  450,  450,  450,  450,  450,  450,  451,  451,  452,
      452,  453,  453,  454,  454,  455,  455,  456,  456,  457,
      457,  457,  457,  457,  457,  457,  457,  457,  457,  457,
      458,  458,  459,  459,  460,  460,  461,  461,  462,  462,
      463,  463,  464,  464,  465,  465,  466,  466,  467,  467,
      299,  294,  293,  284,  283,  282,  281,  276,  273,  260,
      258,  255,  254,  249,  248,  246,  223,  221,  220,  219,
      218,  213,  212,  195,  192,  177,  172,  171,  166,  165,
      159,  150,  149,  148,  147,  146,  145,  138,  135,  120,
      103,   99,   97,   96,   95,   88,   81,   78,   71,   70,

       69,   67,   57,   56,   53,   35,   32,   29,   26,   18,
       16,   12,   11,    7,    2,  404,  404,  404,  404,  404,
      404,  404,  404,  404,  404,  404,  404,  404,  404,  404,
      404,  404,  404,  404,  404,  404,  404,  404,  404,  404,
      404,  404,  404,  404,  404,  404,  404,  404,  404,  404,
      404,  404,  404,  404,  404,  404,  404,  404,  404,  404,
      404,  404,  404,  404,  404,  404,  404,  404,  404,  404,
      404,  404,  404,  404,  404,  404,  404,  404,  404,  404,
      404,  404,  404,  404,  404,  404,  404
    } ;

/* Table of booleans, true if rule could match eol. */
static yyconst flex_int32_t yy_rule_can_match_eol[71] =
    {   0,
0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 
    0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0,     };

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "fb2-5.l"
/* Companion source code for "flex & bison", published by O'Reilly
 * Media, ISBN 978-0-596-15597-1
 * Copyright (c) 2009, Taughannock Networks. All rights reserved.
 * See the README file for license conditions and contact info.
 * $Header: /home/johnl/flnb/code/RCS/fb2-5.l,v 2.1 2009/11/08 02:53:18 johnl Exp $
 */
/* fb2-5 C cross-ref */


/* some complex named patterns */
/* Universal Character Name */
/* float exponent */
/* integer length */
/* the symbol table */
#line 24 "fb2-5.l"
  struct symbol {		/* a variable name */
    struct ref *reflist;
    char *name;
  };

  struct ref {
    struct ref *next;
    char *filename;
    int flags;			/* 01 - definition */
    int lineno;
  };

  /* simple symtab of fixed size */
  #define NHASH 9997
  struct symbol symtab[NHASH];

  struct symbol *lookup(char*);
  void addref(int, char*, char*, int);

  char *curfilename;		/* name of current input file */

  int defining;			/* names are probably definitions */

/* include file stack */  
  struct bufstack {
    struct bufstack *prev;	/* previous entry */
    YY_BUFFER_STATE bs;		/* saved buffer */
    int lineno;			/* saved line number in this file */
    char *filename;		/* name of this file */
    FILE *f;			/* current file */
  } *curbs;

  int newfile(char *fn);
  int popfile(void);

#line 911 "fb2-5.c"

#define INITIAL 0
#define COMMENT 1
#define IFILE 2

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals (void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy (void );

int yyget_debug (void );

void yyset_debug (int debug_flag  );

YY_EXTRA_TYPE yyget_extra (void );

void yyset_extra (YY_EXTRA_TYPE user_defined  );

FILE *yyget_in (void );

void yyset_in  (FILE * in_str  );

FILE *yyget_out (void );

void yyset_out  (FILE * out_str  );

int yyget_leng (void );

char *yyget_text (void );

int yyget_lineno (void );

void yyset_lineno (int line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap (void );
#else
extern int yywrap (void );
#endif
#endif

    static void yyunput (int c,char *buf_ptr  );
    
#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		unsigned n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, yyin))==0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	if ( yyleng > 0 ) \
		YY_CURRENT_BUFFER_LVALUE->yy_at_bol = \
				(yytext[yyleng - 1] == '\n'); \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;
    
#line 60 "fb2-5.l"

 /* comments */
#line 1101 "fb2-5.c"

	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer(yyin,YY_BUF_SIZE );
		}

		yy_load_buffer_state( );
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
		yy_current_state += YY_AT_BOL();
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 405 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 1016 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER && yy_rule_can_match_eol[yy_act] )
			{
			int yyl;
			for ( yyl = 0; yyl < yyleng; ++yyl )
				if ( yytext[yyl] == '\n' )
					   
    yylineno++;
;
			}

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 62 "fb2-5.l"
{ BEGIN(COMMENT) ; }
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 63 "fb2-5.l"
{ BEGIN(INITIAL); }
	YY_BREAK
case 3:
/* rule 3 can match eol */
YY_RULE_SETUP
#line 64 "fb2-5.l"

	YY_BREAK
/* C++ comment, a common extension */
case 4:
/* rule 4 can match eol */
YY_RULE_SETUP
#line 67 "fb2-5.l"

	YY_BREAK
/* declaration keywords */
case 5:
#line 71 "fb2-5.l"
case 6:
#line 72 "fb2-5.l"
case 7:
#line 73 "fb2-5.l"
case 8:
#line 74 "fb2-5.l"
case 9:
#line 75 "fb2-5.l"
case 10:
#line 76 "fb2-5.l"
case 11:
#line 77 "fb2-5.l"
case 12:
#line 78 "fb2-5.l"
case 13:
#line 79 "fb2-5.l"
case 14:
#line 80 "fb2-5.l"
case 15:
#line 81 "fb2-5.l"
case 16:
#line 82 "fb2-5.l"
case 17:
#line 83 "fb2-5.l"
case 18:
#line 84 "fb2-5.l"
case 19:
#line 85 "fb2-5.l"
case 20:
#line 86 "fb2-5.l"
case 21:
#line 87 "fb2-5.l"
case 22:
#line 88 "fb2-5.l"
case 23:
#line 89 "fb2-5.l"
case 24:
#line 90 "fb2-5.l"
case 25:
#line 91 "fb2-5.l"
case 26:
#line 92 "fb2-5.l"
case 27:
#line 93 "fb2-5.l"
case 28:
YY_RULE_SETUP
#line 93 "fb2-5.l"
{ defining = 1; }
	YY_BREAK
/* keywords */
case 29:
YY_RULE_SETUP
#line 97 "fb2-5.l"

	YY_BREAK
case 30:
YY_RULE_SETUP
#line 98 "fb2-5.l"

	YY_BREAK
case 31:
YY_RULE_SETUP
#line 99 "fb2-5.l"

	YY_BREAK
case 32:
YY_RULE_SETUP
#line 100 "fb2-5.l"

	YY_BREAK
case 33:
YY_RULE_SETUP
#line 101 "fb2-5.l"

	YY_BREAK
case 34:
YY_RULE_SETUP
#line 102 "fb2-5.l"

	YY_BREAK
case 35:
YY_RULE_SETUP
#line 103 "fb2-5.l"

	YY_BREAK
case 36:
YY_RULE_SETUP
#line 104 "fb2-5.l"

	YY_BREAK
case 37:
YY_RULE_SETUP
#line 105 "fb2-5.l"

	YY_BREAK
case 38:
YY_RULE_SETUP
#line 106 "fb2-5.l"

	YY_BREAK
case 39:
YY_RULE_SETUP
#line 107 "fb2-5.l"

	YY_BREAK
case 40:
YY_RULE_SETUP
#line 108 "fb2-5.l"

	YY_BREAK
case 41:
YY_RULE_SETUP
#line 109 "fb2-5.l"

	YY_BREAK
/* constants */
/* integers */
case 42:
YY_RULE_SETUP
#line 114 "fb2-5.l"

	YY_BREAK
case 43:
YY_RULE_SETUP
#line 115 "fb2-5.l"

	YY_BREAK
case 44:
YY_RULE_SETUP
#line 116 "fb2-5.l"

	YY_BREAK
/* decimal float */
case 45:
YY_RULE_SETUP
#line 119 "fb2-5.l"

	YY_BREAK
case 46:
YY_RULE_SETUP
#line 120 "fb2-5.l"

	YY_BREAK
/* hex float */
case 47:
YY_RULE_SETUP
#line 123 "fb2-5.l"

	YY_BREAK
/* char const */
case 48:
/* rule 48 can match eol */
YY_RULE_SETUP
#line 127 "fb2-5.l"

	YY_BREAK
/* string literal */
case 49:
/* rule 49 can match eol */
YY_RULE_SETUP
#line 130 "fb2-5.l"

	YY_BREAK
/* punctuators */
case 50:
YY_RULE_SETUP
#line 133 "fb2-5.l"
{ defining = 0; }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 136 "fb2-5.l"

	YY_BREAK
case 52:
YY_RULE_SETUP
#line 137 "fb2-5.l"

	YY_BREAK
case 53:
YY_RULE_SETUP
#line 138 "fb2-5.l"

	YY_BREAK
case 54:
YY_RULE_SETUP
#line 139 "fb2-5.l"

	YY_BREAK
case 55:
YY_RULE_SETUP
#line 140 "fb2-5.l"

	YY_BREAK
case 56:
YY_RULE_SETUP
#line 141 "fb2-5.l"

	YY_BREAK
case 57:
YY_RULE_SETUP
#line 142 "fb2-5.l"

	YY_BREAK
/* identifier */
case 58:
YY_RULE_SETUP
#line 145 "fb2-5.l"
{
                         addref(yylineno, curfilename, yytext, defining); }
	YY_BREAK
/* white space */
case 59:
/* rule 59 can match eol */
YY_RULE_SETUP
#line 149 "fb2-5.l"

	YY_BREAK
/* continued line */
case 60:
*yy_cp = (yy_hold_char); /* undo effects of setting up yytext */
(yy_c_buf_p) = yy_cp -= 1;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 151 "fb2-5.l"

	YY_BREAK
/* some preprocessor stuff */
case 61:
/* rule 61 can match eol */
YY_RULE_SETUP
#line 154 "fb2-5.l"

	YY_BREAK
case 62:
/* rule 62 can match eol */
YY_RULE_SETUP
#line 155 "fb2-5.l"

	YY_BREAK
case 63:
/* rule 63 can match eol */
YY_RULE_SETUP
#line 156 "fb2-5.l"

	YY_BREAK
case 64:
/* rule 64 can match eol */
YY_RULE_SETUP
#line 157 "fb2-5.l"

	YY_BREAK
case 65:
/* rule 65 can match eol */
YY_RULE_SETUP
#line 158 "fb2-5.l"

	YY_BREAK
/* recognize an include */
case 66:
YY_RULE_SETUP
#line 161 "fb2-5.l"
{ BEGIN IFILE; }
	YY_BREAK
case 67:
/* rule 67 can match eol */
YY_RULE_SETUP
#line 163 "fb2-5.l"
{ 
                       { int c;
			 while((c = input()) && c != '\n') ;
		       }
		       newfile(strdup(yytext));
		       BEGIN INITIAL;
                }
	YY_BREAK
case 68:
/* rule 68 can match eol */
YY_RULE_SETUP
#line 171 "fb2-5.l"
{ fprintf(stderr, "%s:%d bad include line\n",
			  curfilename, yylineno);
                  BEGIN INITIAL;
                }
	YY_BREAK
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(COMMENT):
case YY_STATE_EOF(IFILE):
#line 176 "fb2-5.l"
{ if(!popfile()) yyterminate(); }
	YY_BREAK
/* invalid character */
case 69:
YY_RULE_SETUP
#line 179 "fb2-5.l"
{ printf("%s:%d: Mystery character '%s'\n",
			 curfilename, yylineno, yytext);
                }
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 182 "fb2-5.l"
YY_FATAL_ERROR( "flex scanner jammed" );
	YY_BREAK
#line 1525 "fb2-5.c"

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	register char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	register char *source = (yytext_ptr);
	register int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc((void *) b->yy_ch_buf,b->yy_buf_size + 2  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), (size_t) num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart(yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((yy_size_t) ((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		yy_size_t new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	register yy_state_type yy_current_state;
	register char *yy_cp;
    
	yy_current_state = (yy_start);
	yy_current_state += YY_AT_BOL();

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 405 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	register int yy_is_jam;
    	register char *yy_cp = (yy_c_buf_p);

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 405 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 404);

	return yy_is_jam ? 0 : yy_current_state;
}

    static void yyunput (int c, register char * yy_bp )
{
	register char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = (yy_n_chars) + 2;
		register char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		register char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

    if ( c == '\n' ){
        --yylineno;
    }

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart(yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap( ) )
						return EOF;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = (c == '\n');
	if ( YY_CURRENT_BUFFER_LVALUE->yy_at_bol )
		   
    yylineno++;
;

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer(yyin,YY_BUF_SIZE );
	}

	yy_init_buffer(YY_CURRENT_BUFFER,input_file );
	yy_load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree((void *) b->yy_ch_buf  );

	yyfree((void *) b  );
}

#ifndef __cplusplus
extern int isatty (int );
#endif /* __cplusplus */
    
/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	int num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );
								  
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		int grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (yyconst char * yystr )
{
    
	return yy_scan_bytes(yystr,strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param bytes the byte buffer to scan
 * @param len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (yyconst char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) yyalloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg )
{
    	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
        
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param line_number
 * 
 */
void yyset_lineno (int  line_number )
{
    
    yylineno = line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  in_str )
{
        yyin = in_str ;
}

void yyset_out (FILE *  out_str )
{
        yyout = out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  bdebug )
{
        yy_flex_debug = bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    /* We do not touch yylineno unless the option is enabled. */
    yylineno =  1;
    
    (yy_buffer_stack) = 0;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = (char *) 0;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = (FILE *) 0;
    yyout = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
	return (void *) malloc( size );
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void yyfree (void * ptr )
{
	free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 182 "fb2-5.l"



/* hash a symbol */
static unsigned
symhash(char *sym)
{
  unsigned int hash = 0;
  unsigned c;

  while(c = *sym++) hash = hash*9 ^ c;

  return hash;
}

struct symbol *
lookup(char* sym)
{
  struct symbol *sp = &symtab[symhash(sym)%NHASH];
  int scount = NHASH;		/* how many have we looked at */

  while(--scount >= 0) {
    if(sp->name && !strcmp(sp->name, sym)) { return sp; }

    if(!sp->name) {		/* new entry */
      sp->name = strdup(sym);
      sp->reflist = 0;
      return sp;
    }

    if(++sp >= symtab+NHASH) sp = symtab; /* try the next entry */
  }
  fputs("symbol table overflow\n", stderr);
  abort(); /* tried them all, table is full */

}

void
addref(int lineno, char *filename, char *word, int flags)
{
  struct ref *r;
  struct symbol *sp = lookup(word);

  /* don't do dups */
  if(sp->reflist &&
     sp->reflist->lineno == lineno && sp->reflist->filename == filename) return;

  r = malloc(sizeof(struct ref));
  if(!r) {fputs("out of space\n", stderr); abort(); }
  r->next = sp->reflist;
  r->filename = filename;
  r->lineno = lineno;
  r->flags = flags;
  sp->reflist = r;
}

/* print the references
 * sort the table alphabetically
 * then flip each entry's reflist to get it into forward order
 * and print it out 
 */

/* aux function for sorting */
static int
symcompare(const void *xa, const void *xb)
{
  const struct symbol *a = xa;
  const struct symbol *b = xb;

  if(!a->name) {
    if(!b->name) return 0;	/* both empty */
    return 1;			/* put empties at the end */
  }
  if(!b->name) return -1;
  return strcmp(a->name, b->name);
}

void
printrefs()
{
  struct symbol *sp;

  qsort(symtab, NHASH, sizeof(struct symbol), symcompare); /* sort the symbol table */

  for(sp = symtab; sp->name && sp < symtab+NHASH; sp++) {
    char *prevfn = NULL;	/* last printed filename, to skip dups */

    /* reverse the list of references */
    struct ref *rp = sp->reflist;
    struct ref *rpp = 0;	/* previous ref */
    struct ref *rpn;	/* next ref */

    do {
      rpn = rp->next;
      rp->next = rpp;
      rpp = rp;
      rp = rpn;
    } while(rp);

    /* now print the word and its references */
    printf("%10s", sp->name);
    for(rp = rpp; rp; rp = rp->next) {
      if(rp->filename == prevfn) {
	printf(" %d", rp->lineno);
      } else {
	printf(" %s:%d", rp->filename, rp->lineno);
	prevfn = rp->filename;
      }
      if(rp->flags & 01) printf("*");
    }
    printf("\n");
  }
}

int
main(argc, argv)
int argc;
char **argv;
{
  int i;

  if(argc < 2) {
    fprintf(stderr, "need filename\n");
    return 1;
  }
  for(i = 1; i < argc; i++) {
    if(newfile(argv[i])) yylex();
  }

  printrefs();
  return 0;
}

/* nested input files */
int
  newfile(char *fn)
{
  FILE *f = fopen(fn, "r");
  struct bufstack *bs;

  /* check if no file */
  if(!f) {
    perror(fn);
    return 0;
  }

  bs = malloc(sizeof(struct bufstack));
  if(!bs) { perror("malloc"); exit(1); }

  /* remember state */
  if(curbs) curbs->lineno = yylineno;

  bs->prev = curbs;
  bs->f = f;
  bs->filename = fn;

  /* set up current entry */
  bs->bs = yy_create_buffer(f,YY_BUF_SIZE);
  yy_switch_to_buffer(bs->bs);
  curbs = bs;
  yylineno = 1;
  curfilename = fn;
  return 1;
}

int
  popfile(void)
{
  struct bufstack *bs = curbs;
  struct bufstack *prevbs;

  if(!bs) return 0;

  /* get rid of current entry
  fclose(bs->f);
  yy_delete_buffer(bs->bs);

  /* switch back to previous */
  prevbs = bs->prev;
  free(bs);

  if(!prevbs) return 0;

  yy_switch_to_buffer(prevbs->bs);
  curbs = prevbs;
  yylineno = curbs->lineno;
  curfilename = curbs->filename;
  return 1; 
}

