######################################################################
# Automatically generated by qmake (2.01a) Mon Aug 3 09:42:47 2015
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += mainwindow.cpp
