#!/bin/sh

rm -rf fred*  #强制且递归删除fred开头的文件和文件夹
echo > fred1	#创建文件fred1  touch fred1功能相同
echo > fred2	#创建文件fred2
mkdir fred3	#创建文件夹fred3
echo > fred4	#创建文件fred4
touch fred5
file fred5		#显示文件的属性，但是不会创建文件
file fred3
#mkdir fred6

#---------------------------------------------------
#	相当于touch fred1  
#---------------------------------------------------

#for file in fred*		#其实通配符是for循环的主要用法，而且最好不要用file做变量，因为
#do					#file是一个指令，
for file in `ls -l ./`
do
	if [ -d "$file" ]; then
	echo first directory fred was $file	
	fi
done

#echo first directory fred was $file		#echo可以给个能多的提示信息

rm -rf fred*
#ls -l

exit 0 
