#!/bin/sh

#---------------------------------------------------
#	who whoami  id finger 
#	who 显示目前登入系统的用户信息
#	whoami显示自身的用户名称，本指令相当于执行"id -un"指令
#	id id会显示用户以及所属群组的实际与有效ID。若两个ID相同，则仅显示实际ID。
#	finger	查找并显示用户信息。
#	su chfn chsh 
#	which whichis 查找文件
#	wc 计算字数。wc(word count)
#	tr	tr(translate character)
#---------------------------------------------------
until who | grep "$1" > /dev/null
do
  echo "222222222222222222222"
  sleep 60
done

who
# Now ring the bell and announce the unexpected user.

echo -e \\a
echo "***** $1 has just logged in *****"

exit 0
