#!/bin/sh

touch file_one
touch file_three
rm -f file_two #-f force -r recursve

#---------------------------------------------------
#	"与"如果判断最左边的某个值是FALSE
#	右边的条件就不用进行判断了，直接
#	执行else语句
#---------------------------------------------------

#---------------------------------------------------
#	"与"一般还是用&&为好，-a 不能用到
#	一些简单的声明，如:echo "there"	
#---------------------------------------------------
#	test -f file_one

#if [ -f file_one ] && echo "hello" && [ -f file_two ] && echo "there"	#判断语句中，由于第一个肯定成了，所以执行
#then													#echo "hello" ，但是[ -f file_two ] 不成立，导致下一个不执行
#if [ -f file_one -a echo "hello" -o -f file_two -a echo "there" ]		#NO
#if [ -f file_one -a -f file_two ] && echo "hello" && echo "there"	#OK
#if [ -f file_one -a -f file_three  -a -f file_two ]                              #OK
if  echo "there" 											#OK
if [echo "there"]											#NO
then
   echo -e "in if"
else
    echo -e "in else"
fi

rm -f file_one
rm -f file_three

exit 0
