#!/bin/sh

#-----------------------------------------------------
#   该用法，通用而简单！
#	
#-----------------------------------------------------

echo "Is it morning? Please answer yes or no"
read timeofday

#其实该处可以用通配符，但是一定要简单有效
#[Yy][Ee][Ss]  [Nn][Oo] 但是这样仍然不能包含像Nn Ys这样的
#简单应答的问题，

case "$timeofday" in

# "yes") echo "Good Morning";;
#"no" ) echo "Good Afternoon";;   
#"y"  ) echo "Good Morning";;
#"n"  ) echo "Good Afternoon";;   
	[Yy][Ee][Ss] | [Yy]) echo "Good Morning";;
	[Nn][Oo] | [Nn] ) echo "Good Afternoon";;   
	*    ) echo "Sorry, answer not recognised";;
esac

exit 0 
