#!/bin/sh

#-----------------------------------------------------
#   case 中的选择可以用了 | 来取或
#	主要学习通配符的用法和散转的用法
#-----------------------------------------------------

echo "Is it morning? Please answer yes or no"
read timeofday

case "$timeofday" in
    yes | y | Yes | YES ) 
           echo "Good Morning"
           echo "Up bright and early this morning?"
           ;;
    [nN]* )  
           echo "Good Afternoon"
           ;;   
    * )    
           echo "Sorry, answer not recognised"
           echo "Please answer yes or no"
           exit 1
           ;;
esac

exit 0 
