#!/bin/sh

#-----------------------------------------------------
#   虽然在这里用到了通配符，但是这样用通配符还是有很大的
#	误区，照成了，以N n开有的输入变成了否认！
#-----------------------------------------------------

echo "Is it morning? Please answer yes or no"
#read timeofday						#读取输入的数值timeofday中包含

read 
#case "$timeofday" in
case "$REPLY" in  	#$REPLY默认的情况下
    yes | y | Yes | YES ) echo "Good Morning";;
    n*  | N* )                echo "Good Afternoon";;   
    * )                           echo "Sorry, answer not recognised";;
esac

exit 0 
