#!/bin/sh

#-----------------------------------------------------
#   version和Path仅仅在自身的程序空间中有用处，在其他的
#	程序空间，没有作用，
#	 即使使用了export的语句，也只能让它调用的shell感应到
#	系统的环境变量是感应不到的
#-----------------------------------------------------

version=classic
PATH=/usr/local/old_bin:/usr/bin:/bin:.
USER=wangfl
export USER
export PATH
PS1="classic> "

