#!/bin/sh

#-----------------------------------------------------
#   通过简单的重定向命令，可以创建文件，
#	与break相对应，是continue的应用，该应用用以显示
#	所以的文件，不显示文件夹
#-----------------------------------------------------

rm -rf fred*
echo > fred1
echo > fred2
mkdir fred3
echo > fred4
				#最好的方法使用ls来代替，这样更准确，也利于学习
for file in 	`ls ./`	#简单的一个*,代表当前文件夹下所有的文件的名称
do
  if [ -d "$file" ]; then
    echo "skipping directory $file"
    cd ./"$file"
    ls
   pwd
   cd ../../
   pwd
    #    continue
  fi
 # echo file is $file
done

rm -rf fred*

exit 0 
