#!/bin/sh

#---------------------------------------------------
#以最简单的方法介绍了continue关键字的应用
#---------------------------------------------------

for x in 1 2 3
do
    echo before $x
    continue 			#没有判断的continue搞得下面的都不执行
    echo after $x
done

exit 0
