#!/bin/sh

#---------------------------------------------------
#	讲究判断语句的应用，判断语句
#	if [判断条件] 
#	then 
#	[执行语句]
#	elif [判断条件]
#	then 
#	[执行语句]
#	...   ....   			... ...
#	else
#	[执行语句]
#	fi
#	备注:显示了case 的强大作用
#---------------------------------------------------

echo "Is it morning? Please answer yes or no"
read timeofday

if [ $timeofday = "yes" ]
then
  echo "Good morning"
elif [ $timeofday = "no" ]; then
  echo "Good afternoon"
else
  echo "Sorry, $timeofday not recognized. Enter yes or no"
  exit 1
fi

exit 0 
