#!/bin/sh

#-----------------------------------------------------
#	可以通过，一个shell文件，调用另一个shell文件
#   export通过该关键字，可以将变量在文件之间传递
#-----------------------------------------------------

foo="The first meta-syntactic variable"
export bar="The second meta-syntactic variable"

./export2
