#!/bin/sh

# first.sh
# This file looks through all the files in the current
# directory for the string POSIX, and then prints those
# files to the standard output.

#-----------------------------------------------------
#	在当前的文件中，查找那个文件包含POSIX
#-----------------------------------------------------

for file in *		#最好用`ls`语句
do
	echo "${file}"
  if grep -q first $file 	#从一个文件中查找一个值该值的名称叫POSIX
  then
  more $file 
  fi
done

exit 0
