#!/bin/sh

#----------------------------------------------------
#	简单的一个函数
#----------------------------------------------------

foo() {
    echo "Function foo is executing"
}

echo "script starting"
foo
echo "script ended"

exit 0
