#!/bin/sh

#-----------------------------------------------------
#  函数可以通过返回值，用来设定下面的执行情况！
#  函数也分全局变量，局部变量。
#  外部声明的变量，在函数中可以被赋值，同时也能过被外部的
#  识别。能过把函数中的值传出来，也可以用return 返回False True
#  内部变量，不能被外部的程序用到！因为shell也讲究“作用域”
#  注：文件的位置变量是全局变量
#-----------------------------------------------------

sample_text="global variable"

foo() {
    local sample_text="local variable"		#关键字local  标识该变量是局部的，虽然和全局的名字一样

    echo "Function foo is executing"
    echo $sample_text
}

echo "script starting"
echo $sample_text

foo						#函数的作用，相当于一个命令，更像一个程序

echo "script ended"
echo $sample_text

exit 0
