#!/bin/sh

#-----------------------------------------------------
#  函数可以通过返回值，用来设定下面的执行情况！
#  函数也分全局变量，局部变量。
#  外部声明的变量，在函数中可以被赋值，同时也能过被外部的
#  识别。能过把函数中的值传出来，也可以用return 返回False True
#  内部变量，不能被外部的程序用到！因为shell也讲究“作用域”
#  注：文件的位置变量是全局变量
#-----------------------------------------------------

yes_or_no() {
  echo "Is your name $* ?"
  while true
  do
    echo -n "Enter yes or no: "
    read x
    case "$x" in
      y | yes | Y | Yes | YES) return 0;;
      n | no | N | No | NO)  return 1;;
      * )       echo "Answer yes or no"
    esac
  done
}

echo "Original parameters are $*"

if yes_or_no "$1"
then
  echo "Hi $1, nice name"
else
  echo "Never mind"
fi

exit 0
