#!/bin/sh

#-----------------------------------------------------
#  由于删除了file_one文件，那么该文件肯定不存在，所以
#  [ -f file_one ]肯定输出为假，所以echo "hello"会被执行
#  但是echo "there"不会被执行！
#-----------------------------------------------------

rm -f file_one

if [ -f file_one ] || echo "hello" || echo "there"
then
    echo "in if"
else
    echo "in else"
fi

exit 0
