#!/bin/sh

#-----------------------------------------------------
#  字符串的处理
#  显示的和变量获得有时候会有差距
#-----------------------------------------------------

value=

unset foo						#在这里的值，和下面的一样
foo=							#
bar=boll
echo value=${foo:-bar} 		#echo 语句只是如是的现实要显示的，不会修改value的值
value=${foo:-bar} 			#当下执行的是赋值语句，就是将判断的值赋给value
echo "----------${value}"

foo=fud
echo value=${foo:-bar}
value=${foo:-bar}
echo "==========${value}"

foo=/usr/bin/X11/startx
echo ${foo#*/}
echo ${foo##*/}

bar=/usr/local/etc/local/networks
echo ${bar%local*}
echo ${bar%%local*}

exit 0

