#!/bin/sh

#-----------------------------------------------------
#  变量的应用
#
#-----------------------------------------------------

myvar="Hi there"

echo $myvar		#Hi there
echo "$myvar"	#Hi there
echo '$myvar'		#$myvar
echo \$myvar		#$myvar

echo Enter some text
read myvar

echo '$myvar' now equals $myvar  #等于输入的值

exit 0
