######################################################################
# Automatically generated by qmake (2.01a) Mon Aug 3 11:38:02 2015
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += Calculator.h
SOURCES += Calculator.cpp main.cpp
