/* AUTOGENERATED FILE. DO NOT EDIT. */

//=======Test Runner Used To Run Each Test Below=====
#define RUN_TEST(TestFunc, TestLineNum) \
{ \
  Unity.CurrentTestName = #TestFunc; \
  Unity.CurrentTestLineNumber = TestLineNum; \
  Unity.NumberOfTests++; \
  if (TEST_PROTECT()) \
  { \
      setUp(); \
      TestFunc(); \
  } \
  if (TEST_PROTECT() && !TEST_IS_IGNORED) \
  { \
    tearDown(); \
  } \
  UnityConcludeTest(); \
}

//=======Automagically Detected Files To Include=====
#include "unity.h"
#include <setjmp.h>
#include <stdio.h>
#include "../selection_sort.h"
#include <stdlib.h>
#include <stdio.h>
#include <assert.h>

//=======External Functions This Runner Calls=====
extern void setUp(void);
extern void tearDown(void);
extern void test_selection_sort_on_null_array();
extern void test_selection_sort_on_full_array();
extern void test_selection_sort_on_full_ptr_array();


//=======Test Reset Option=====
void resetTest(void);
void resetTest(void)
{
  tearDown();
  setUp();
}


//=======MAIN=====
int main(void)
{
  UnityBegin("selection_sort_test.c");
  RUN_TEST(test_selection_sort_on_null_array, 52);
  RUN_TEST(test_selection_sort_on_full_array, 59);
  RUN_TEST(test_selection_sort_on_full_ptr_array, 73);

  return (UnityEnd());
}
